domain_path: E:\Dev\QianSal\mipi_dp_vitis\mipi_dp\export\mipi_dp\sw\standalone_psu_cortexa53_0
app_src_dir: C:\Xilinx\Vitis\2024.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
