# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Dev/QianSai/mipi_dp_vivado/mipi_dp.srcs/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/design_1_v_demosaic_0_2.xci
# IP: The module: 'design_1_v_demosaic_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Dev/QianSai/mipi_dp_vivado/mipi_dp.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/design_1_v_demosaic_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_v_demosaic_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Dev/QianSai/mipi_dp_vivado/mipi_dp.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/design_1_v_demosaic_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_v_demosaic_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/Dev/QianSai/mipi_dp_vivado/mipi_dp.srcs/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/design_1_v_demosaic_0_2.xci
# IP: The module: 'design_1_v_demosaic_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Dev/QianSai/mipi_dp_vivado/mipi_dp.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/design_1_v_demosaic_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_v_demosaic_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Dev/QianSai/mipi_dp_vivado/mipi_dp.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/design_1_v_demosaic_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_v_demosaic_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
