# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/mipi.xdc

# XDC: new/system.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_vdma_0_0/design_1_axi_vdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_vdma_0_0 || ORIG_REF_NAME==design_1_axi_vdma_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_subset_converter_0_0/design_1_axis_subset_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_subset_converter_0_0 || ORIG_REF_NAME==design_1_axis_subset_converter_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/design_1_mipi_csi2_rx_subsyst_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mipi_csi2_rx_subsyst_0_0 || ORIG_REF_NAME==design_1_mipi_csi2_rx_subsyst_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_1_0/design_1_mipi_csi2_rx_subsyst_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mipi_csi2_rx_subsyst_1_0 || ORIG_REF_NAME==design_1_mipi_csi2_rx_subsyst_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_150M_0/design_1_proc_sys_reset_150M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_150M_0 || ORIG_REF_NAME==design_1_proc_sys_reset_150M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps8_0_axi_periph_upgraded_ipi_imp_xbar_0/design_1_ps8_0_axi_periph_upgraded_ipi_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps8_0_axi_periph_upgraded_ipi_imp_xbar_0 || ORIG_REF_NAME==design_1_ps8_0_axi_periph_upgraded_ipi_imp_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps8_0_axi_periph_0/design_1_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps8_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_0/design_1_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_demosaic_0_2/design_1_v_demosaic_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_v_demosaic_0_2 || ORIG_REF_NAME==design_1_v_demosaic_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_0/design_1_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_0 || ORIG_REF_NAME==design_1_smartconnect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_demosaic_1_0/design_1_v_demosaic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_v_demosaic_1_0 || ORIG_REF_NAME==design_1_v_demosaic_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_subset_converter_1_0/design_1_axis_subset_converter_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_subset_converter_1_0 || ORIG_REF_NAME==design_1_axis_subset_converter_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_gamma_lut_0_0/design_1_v_gamma_lut_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_v_gamma_lut_0_0 || ORIG_REF_NAME==design_1_v_gamma_lut_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_gamma_lut_1_0/design_1_v_gamma_lut_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_v_gamma_lut_1_0 || ORIG_REF_NAME==design_1_v_gamma_lut_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_vdma_1_0/design_1_axi_vdma_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_vdma_1_0 || ORIG_REF_NAME==design_1_axi_vdma_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps8_0_axi_periph_imp_auto_pc_0/design_1_ps8_0_axi_periph_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps8_0_axi_periph_imp_auto_pc_0 || ORIG_REF_NAME==design_1_ps8_0_axi_periph_imp_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps8_0_axi_periph_imp_auto_pc_1/design_1_ps8_0_axi_periph_imp_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps8_0_axi_periph_imp_auto_pc_1 || ORIG_REF_NAME==design_1_ps8_0_axi_periph_imp_auto_pc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps8_0_axi_periph_imp_auto_pc_2/design_1_ps8_0_axi_periph_imp_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps8_0_axi_periph_imp_auto_pc_2 || ORIG_REF_NAME==design_1_ps8_0_axi_periph_imp_auto_pc_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps8_0_axi_periph_imp_auto_pc_3/design_1_ps8_0_axi_periph_imp_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps8_0_axi_periph_imp_auto_pc_3 || ORIG_REF_NAME==design_1_ps8_0_axi_periph_imp_auto_pc_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps8_0_axi_periph_imp_auto_pc_4/design_1_ps8_0_axi_periph_imp_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps8_0_axi_periph_imp_auto_pc_4 || ORIG_REF_NAME==design_1_ps8_0_axi_periph_imp_auto_pc_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps8_0_axi_periph_imp_auto_pc_5/design_1_ps8_0_axi_periph_imp_auto_pc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps8_0_axi_periph_imp_auto_pc_5 || ORIG_REF_NAME==design_1_ps8_0_axi_periph_imp_auto_pc_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps8_0_axi_periph_imp_auto_pc_6/design_1_ps8_0_axi_periph_imp_auto_pc_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps8_0_axi_periph_imp_auto_pc_6 || ORIG_REF_NAME==design_1_ps8_0_axi_periph_imp_auto_pc_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps8_0_axi_periph_imp_auto_pc_7/design_1_ps8_0_axi_periph_imp_auto_pc_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps8_0_axi_periph_imp_auto_pc_7 || ORIG_REF_NAME==design_1_ps8_0_axi_periph_imp_auto_pc_7} -quiet] -quiet

# XDC: e:/Dev/QianSai/mipi_dp_vivado/mipi_dp.gen/sources_1/bd/design_1/design_1_ooc.xdc
