// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module design_1_v_demosaic_0_2_DebayerRatBorBatR (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        imgG_dout,
        imgG_empty_n,
        imgG_read,
        imgG_num_data_valid,
        imgG_fifo_cap,
        imgRB_din,
        imgRB_full_n,
        imgRB_write,
        imgRB_num_data_valid,
        imgRB_fifo_cap,
        height_val4_dout,
        height_val4_empty_n,
        height_val4_read,
        height_val4_num_data_valid,
        height_val4_fifo_cap,
        width_val8_dout,
        width_val8_empty_n,
        width_val8_read,
        width_val8_num_data_valid,
        width_val8_fifo_cap,
        bayerPhase_val11_dout,
        bayerPhase_val11_empty_n,
        bayerPhase_val11_read,
        bayerPhase_val11_num_data_valid,
        bayerPhase_val11_fifo_cap,
        height_val4_c_din,
        height_val4_c_full_n,
        height_val4_c_write,
        height_val4_c_num_data_valid,
        height_val4_c_fifo_cap,
        width_val8_c_din,
        width_val8_c_full_n,
        width_val8_c_write,
        width_val8_c_num_data_valid,
        width_val8_c_fifo_cap,
        bayerPhase_val11_c_din,
        bayerPhase_val11_c_full_n,
        bayerPhase_val11_c_write,
        bayerPhase_val11_c_num_data_valid,
        bayerPhase_val11_c_fifo_cap
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [29:0] imgG_dout;
input   imgG_empty_n;
output   imgG_read;
input  [2:0] imgG_num_data_valid;
input  [2:0] imgG_fifo_cap;
output  [29:0] imgRB_din;
input   imgRB_full_n;
output   imgRB_write;
input  [31:0] imgRB_num_data_valid;
input  [31:0] imgRB_fifo_cap;
input  [10:0] height_val4_dout;
input   height_val4_empty_n;
output   height_val4_read;
input  [2:0] height_val4_num_data_valid;
input  [2:0] height_val4_fifo_cap;
input  [10:0] width_val8_dout;
input   width_val8_empty_n;
output   width_val8_read;
input  [2:0] width_val8_num_data_valid;
input  [2:0] width_val8_fifo_cap;
input  [15:0] bayerPhase_val11_dout;
input   bayerPhase_val11_empty_n;
output   bayerPhase_val11_read;
input  [2:0] bayerPhase_val11_num_data_valid;
input  [2:0] bayerPhase_val11_fifo_cap;
output  [10:0] height_val4_c_din;
input   height_val4_c_full_n;
output   height_val4_c_write;
input  [2:0] height_val4_c_num_data_valid;
input  [2:0] height_val4_c_fifo_cap;
output  [10:0] width_val8_c_din;
input   width_val8_c_full_n;
output   width_val8_c_write;
input  [2:0] width_val8_c_num_data_valid;
input  [2:0] width_val8_c_fifo_cap;
output  [15:0] bayerPhase_val11_c_din;
input   bayerPhase_val11_c_full_n;
output   bayerPhase_val11_c_write;
input  [2:0] bayerPhase_val11_c_num_data_valid;
input  [2:0] bayerPhase_val11_c_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg height_val4_read;
reg width_val8_read;
reg bayerPhase_val11_read;
reg height_val4_c_write;
reg width_val8_c_write;
reg bayerPhase_val11_c_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    height_val4_blk_n;
reg    width_val8_blk_n;
reg    bayerPhase_val11_blk_n;
reg    height_val4_c_blk_n;
reg    width_val8_c_blk_n;
reg    bayerPhase_val11_c_blk_n;
reg   [10:0] width_val8_read_reg_436;
reg    ap_block_state1;
reg   [10:0] height_val4_read_reg_441;
wire   [0:0] x_phase_fu_223_p1;
reg   [0:0] x_phase_reg_446;
wire   [10:0] loopHeight_fu_227_p2;
reg   [10:0] loopHeight_reg_451;
wire   [10:0] loopWidth_fu_233_p2;
reg   [10:0] loopWidth_reg_456;
reg   [14:0] trunc_ln_reg_461;
reg   [10:0] y_3_reg_467;
wire    ap_CS_fsm_state2;
reg   [9:0] p_0_0_09411390_lcssa1442_i_load_reg_476;
reg   [9:0] p_0_0_09401393_lcssa1444_i_load_reg_481;
reg   [9:0] p_0_0_09391396_lcssa1446_i_load_reg_486;
reg   [9:0] p_0_0_0941_21420_lcssa1454_i_load_reg_491;
reg   [9:0] p_0_0_0940_21423_lcssa1456_i_load_reg_496;
reg   [9:0] p_0_0_0939_21426_lcssa1458_i_load_reg_501;
reg   [9:0] p_0_0_0_0_09141487_lcssa1524_i_load_reg_506;
reg   [9:0] p_0_1_0_0_09151489_lcssa1526_i_load_reg_511;
reg   [9:0] p_0_2_0_0_09161491_lcssa1528_i_load_reg_516;
reg   [9:0] p_0_0_0941_114821494_lcssa1530_i_load_reg_521;
reg   [9:0] p_0_0_0940_114841496_lcssa1532_i_load_reg_526;
reg   [9:0] p_0_0_0939_114861498_lcssa1534_i_load_reg_531;
reg   [9:0] p_0_0_0_0_09081499_lcssa1536_i_load_reg_536;
reg   [9:0] p_0_1_0_0_09091501_lcssa1538_i_load_reg_541;
reg   [9:0] p_0_2_0_0_09101503_lcssa1540_i_load_reg_546;
wire   [0:0] trunc_ln630_fu_318_p1;
reg   [0:0] trunc_ln630_reg_551;
wire    ap_CS_fsm_state3;
wire   [0:0] and310_i_fu_322_p2;
reg   [0:0] and310_i_reg_556;
wire   [14:0] xor_i_fu_333_p2;
reg   [14:0] xor_i_reg_561;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_start;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_done;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_idle;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_ready;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_imgG_read;
wire   [29:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_imgRB_din;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_imgRB_write;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_2_0_0_09101504_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_2_0_0_09101504_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_1_0_0_09091502_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_1_0_0_09091502_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0_0_09081500_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0_0_09081500_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0939_114861497_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0939_114861497_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0940_114841495_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0940_114841495_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0941_114821493_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0941_114821493_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_2_0_0_09161492_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_2_0_0_09161492_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_1_0_0_09151490_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_1_0_0_09151490_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0_0_09141488_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0_0_09141488_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0939_21425_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0939_21425_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0940_21422_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0940_21422_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0941_21419_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0941_21419_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09391395_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09391395_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09401392_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09401392_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09411389_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09411389_i_out_ap_vld;
reg    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_start_reg;
wire    ap_CS_fsm_state4;
reg   [9:0] p_0_2_0_0_09101503_lcssa1540_i_fu_130;
reg   [9:0] p_0_1_0_0_09091501_lcssa1538_i_fu_126;
reg   [9:0] p_0_0_0_0_09081499_lcssa1536_i_fu_122;
reg   [9:0] p_0_0_0939_114861498_lcssa1534_i_fu_118;
reg   [9:0] p_0_0_0940_114841496_lcssa1532_i_fu_114;
reg   [9:0] p_0_0_0941_114821494_lcssa1530_i_fu_110;
reg   [9:0] p_0_2_0_0_09161491_lcssa1528_i_fu_106;
reg   [9:0] p_0_1_0_0_09151489_lcssa1526_i_fu_102;
reg   [9:0] p_0_0_0_0_09141487_lcssa1524_i_fu_98;
reg   [9:0] p_0_0_0939_21426_lcssa1458_i_fu_94;
reg   [9:0] p_0_0_0940_21423_lcssa1456_i_fu_90;
reg   [9:0] p_0_0_0941_21420_lcssa1454_i_fu_86;
reg   [9:0] p_0_0_09391396_lcssa1446_i_fu_82;
reg   [9:0] p_0_0_09401393_lcssa1444_i_fu_78;
reg   [9:0] p_0_0_09411390_lcssa1442_i_fu_74;
reg   [10:0] y_fu_70;
wire   [10:0] y_4_fu_262_p2;
wire   [0:0] icmp_ln630_fu_257_p2;
wire   [14:0] and310_cast_i_fu_329_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_start_reg = 1'b0;
#0 y_fu_70 = 11'd0;
end

design_1_v_demosaic_0_2_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2 grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_start),
    .ap_done(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_done),
    .ap_idle(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_idle),
    .ap_ready(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_ready),
    .imgG_dout(imgG_dout),
    .imgG_empty_n(imgG_empty_n),
    .imgG_read(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_imgG_read),
    .imgG_num_data_valid(3'd0),
    .imgG_fifo_cap(3'd0),
    .imgRB_din(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_imgRB_din),
    .imgRB_full_n(imgRB_full_n),
    .imgRB_write(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_imgRB_write),
    .imgRB_num_data_valid(imgRB_num_data_valid),
    .imgRB_fifo_cap(imgRB_fifo_cap),
    .p_0_2_0_0_09101503_lcssa1540_i(p_0_2_0_0_09101503_lcssa1540_i_load_reg_546),
    .p_0_1_0_0_09091501_lcssa1538_i(p_0_1_0_0_09091501_lcssa1538_i_load_reg_541),
    .p_0_0_0_0_09081499_lcssa1536_i(p_0_0_0_0_09081499_lcssa1536_i_load_reg_536),
    .p_0_0_0939_114861498_lcssa1534_i(p_0_0_0939_114861498_lcssa1534_i_load_reg_531),
    .p_0_0_0940_114841496_lcssa1532_i(p_0_0_0940_114841496_lcssa1532_i_load_reg_526),
    .p_0_0_0941_114821494_lcssa1530_i(p_0_0_0941_114821494_lcssa1530_i_load_reg_521),
    .p_0_2_0_0_09161491_lcssa1528_i(p_0_2_0_0_09161491_lcssa1528_i_load_reg_516),
    .p_0_1_0_0_09151489_lcssa1526_i(p_0_1_0_0_09151489_lcssa1526_i_load_reg_511),
    .p_0_0_0_0_09141487_lcssa1524_i(p_0_0_0_0_09141487_lcssa1524_i_load_reg_506),
    .p_0_0_0939_21426_lcssa1458_i(p_0_0_0939_21426_lcssa1458_i_load_reg_501),
    .p_0_0_0940_21423_lcssa1456_i(p_0_0_0940_21423_lcssa1456_i_load_reg_496),
    .p_0_0_0941_21420_lcssa1454_i(p_0_0_0941_21420_lcssa1454_i_load_reg_491),
    .p_0_0_09391396_lcssa1446_i(p_0_0_09391396_lcssa1446_i_load_reg_486),
    .p_0_0_09401393_lcssa1444_i(p_0_0_09401393_lcssa1444_i_load_reg_481),
    .p_0_0_09411390_lcssa1442_i(p_0_0_09411390_lcssa1442_i_load_reg_476),
    .loopWidth(loopWidth_reg_456),
    .empty_58(x_phase_reg_446),
    .xor_i(xor_i_reg_561),
    .width_val8_load(width_val8_read_reg_436),
    .and310_cast_i(and310_i_reg_556),
    .trunc_ln(trunc_ln_reg_461),
    .empty(trunc_ln630_reg_551),
    .y(y_3_reg_467),
    .height_val4_load(height_val4_read_reg_441),
    .p_0_2_0_0_09101504_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_2_0_0_09101504_i_out),
    .p_0_2_0_0_09101504_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_2_0_0_09101504_i_out_ap_vld),
    .p_0_1_0_0_09091502_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_1_0_0_09091502_i_out),
    .p_0_1_0_0_09091502_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_1_0_0_09091502_i_out_ap_vld),
    .p_0_0_0_0_09081500_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0_0_09081500_i_out),
    .p_0_0_0_0_09081500_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0_0_09081500_i_out_ap_vld),
    .p_0_0_0939_114861497_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0939_114861497_i_out),
    .p_0_0_0939_114861497_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0939_114861497_i_out_ap_vld),
    .p_0_0_0940_114841495_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0940_114841495_i_out),
    .p_0_0_0940_114841495_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0940_114841495_i_out_ap_vld),
    .p_0_0_0941_114821493_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0941_114821493_i_out),
    .p_0_0_0941_114821493_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0941_114821493_i_out_ap_vld),
    .p_0_2_0_0_09161492_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_2_0_0_09161492_i_out),
    .p_0_2_0_0_09161492_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_2_0_0_09161492_i_out_ap_vld),
    .p_0_1_0_0_09151490_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_1_0_0_09151490_i_out),
    .p_0_1_0_0_09151490_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_1_0_0_09151490_i_out_ap_vld),
    .p_0_0_0_0_09141488_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0_0_09141488_i_out),
    .p_0_0_0_0_09141488_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0_0_09141488_i_out_ap_vld),
    .p_0_0_0939_21425_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0939_21425_i_out),
    .p_0_0_0939_21425_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0939_21425_i_out_ap_vld),
    .p_0_0_0940_21422_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0940_21422_i_out),
    .p_0_0_0940_21422_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0940_21422_i_out_ap_vld),
    .p_0_0_0941_21419_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0941_21419_i_out),
    .p_0_0_0941_21419_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0941_21419_i_out_ap_vld),
    .p_0_0_09391395_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09391395_i_out),
    .p_0_0_09391395_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09391395_i_out_ap_vld),
    .p_0_0_09401392_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09401392_i_out),
    .p_0_0_09401392_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09401392_i_out_ap_vld),
    .p_0_0_09411389_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09411389_i_out),
    .p_0_0_09411389_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09411389_i_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln630_fu_257_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_start_reg <= 1'b1;
        end else if ((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_ready == 1'b1)) begin
            grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        y_fu_70 <= 11'd0;
    end else if (((icmp_ln630_fu_257_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        y_fu_70 <= y_4_fu_262_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        and310_i_reg_556 <= and310_i_fu_322_p2;
        trunc_ln630_reg_551 <= trunc_ln630_fu_318_p1;
        xor_i_reg_561 <= xor_i_fu_333_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        height_val4_read_reg_441 <= height_val4_dout;
        loopHeight_reg_451 <= loopHeight_fu_227_p2;
        loopWidth_reg_456 <= loopWidth_fu_233_p2;
        trunc_ln_reg_461 <= {{bayerPhase_val11_dout[15:1]}};
        width_val8_read_reg_436 <= width_val8_dout;
        x_phase_reg_446 <= x_phase_fu_223_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09391395_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_0_09391396_lcssa1446_i_fu_82 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09391395_i_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        p_0_0_09391396_lcssa1446_i_load_reg_486 <= p_0_0_09391396_lcssa1446_i_fu_82;
        p_0_0_0939_114861498_lcssa1534_i_load_reg_531 <= p_0_0_0939_114861498_lcssa1534_i_fu_118;
        p_0_0_0939_21426_lcssa1458_i_load_reg_501 <= p_0_0_0939_21426_lcssa1458_i_fu_94;
        p_0_0_09401393_lcssa1444_i_load_reg_481 <= p_0_0_09401393_lcssa1444_i_fu_78;
        p_0_0_0940_114841496_lcssa1532_i_load_reg_526 <= p_0_0_0940_114841496_lcssa1532_i_fu_114;
        p_0_0_0940_21423_lcssa1456_i_load_reg_496 <= p_0_0_0940_21423_lcssa1456_i_fu_90;
        p_0_0_09411390_lcssa1442_i_load_reg_476 <= p_0_0_09411390_lcssa1442_i_fu_74;
        p_0_0_0941_114821494_lcssa1530_i_load_reg_521 <= p_0_0_0941_114821494_lcssa1530_i_fu_110;
        p_0_0_0941_21420_lcssa1454_i_load_reg_491 <= p_0_0_0941_21420_lcssa1454_i_fu_86;
        p_0_0_0_0_09081499_lcssa1536_i_load_reg_536 <= p_0_0_0_0_09081499_lcssa1536_i_fu_122;
        p_0_0_0_0_09141487_lcssa1524_i_load_reg_506 <= p_0_0_0_0_09141487_lcssa1524_i_fu_98;
        p_0_1_0_0_09091501_lcssa1538_i_load_reg_541 <= p_0_1_0_0_09091501_lcssa1538_i_fu_126;
        p_0_1_0_0_09151489_lcssa1526_i_load_reg_511 <= p_0_1_0_0_09151489_lcssa1526_i_fu_102;
        p_0_2_0_0_09101503_lcssa1540_i_load_reg_546 <= p_0_2_0_0_09101503_lcssa1540_i_fu_130;
        p_0_2_0_0_09161491_lcssa1528_i_load_reg_516 <= p_0_2_0_0_09161491_lcssa1528_i_fu_106;
        y_3_reg_467 <= y_fu_70;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0939_114861497_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_0_0939_114861498_lcssa1534_i_fu_118 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0939_114861497_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0939_21425_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_0_0939_21426_lcssa1458_i_fu_94 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0939_21425_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09401392_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_0_09401393_lcssa1444_i_fu_78 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09401392_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0940_114841495_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_0_0940_114841496_lcssa1532_i_fu_114 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0940_114841495_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0940_21422_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_0_0940_21423_lcssa1456_i_fu_90 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0940_21422_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09411389_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_0_09411390_lcssa1442_i_fu_74 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09411389_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0941_114821493_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_0_0941_114821494_lcssa1530_i_fu_110 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0941_114821493_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0941_21419_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_0_0941_21420_lcssa1454_i_fu_86 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0941_21419_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0_0_09081500_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_0_0_0_09081499_lcssa1536_i_fu_122 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0_0_09081500_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0_0_09141488_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_0_0_0_09141487_lcssa1524_i_fu_98 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0_0_09141488_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_1_0_0_09091502_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_1_0_0_09091501_lcssa1538_i_fu_126 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_1_0_0_09091502_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_1_0_0_09151490_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_1_0_0_09151489_lcssa1526_i_fu_102 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_1_0_0_09151490_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_2_0_0_09101504_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_2_0_0_09101503_lcssa1540_i_fu_130 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_2_0_0_09101504_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_2_0_0_09161492_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_2_0_0_09161491_lcssa1528_i_fu_106 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_2_0_0_09161492_i_out;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln630_fu_257_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        bayerPhase_val11_blk_n = bayerPhase_val11_empty_n;
    end else begin
        bayerPhase_val11_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        bayerPhase_val11_c_blk_n = bayerPhase_val11_c_full_n;
    end else begin
        bayerPhase_val11_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        bayerPhase_val11_c_write = 1'b1;
    end else begin
        bayerPhase_val11_c_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        bayerPhase_val11_read = 1'b1;
    end else begin
        bayerPhase_val11_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_val4_blk_n = height_val4_empty_n;
    end else begin
        height_val4_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_val4_c_blk_n = height_val4_c_full_n;
    end else begin
        height_val4_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        height_val4_c_write = 1'b1;
    end else begin
        height_val4_c_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        height_val4_read = 1'b1;
    end else begin
        height_val4_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln630_fu_257_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        width_val8_blk_n = width_val8_empty_n;
    end else begin
        width_val8_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        width_val8_c_blk_n = width_val8_c_full_n;
    end else begin
        width_val8_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        width_val8_c_write = 1'b1;
    end else begin
        width_val8_c_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        width_val8_read = 1'b1;
    end else begin
        width_val8_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln630_fu_257_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and310_cast_i_fu_329_p1 = and310_i_fu_322_p2;

assign and310_i_fu_322_p2 = (trunc_ln630_fu_318_p1 ^ 1'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((bayerPhase_val11_c_full_n == 1'b0) | (width_val8_c_full_n == 1'b0) | (height_val4_c_full_n == 1'b0) | (bayerPhase_val11_empty_n == 1'b0) | (width_val8_empty_n == 1'b0) | (height_val4_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign bayerPhase_val11_c_din = bayerPhase_val11_dout;

assign grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_start = grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_start_reg;

assign height_val4_c_din = height_val4_dout;

assign icmp_ln630_fu_257_p2 = ((y_fu_70 == loopHeight_reg_451) ? 1'b1 : 1'b0);

assign imgG_read = grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_imgG_read;

assign imgRB_din = grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_imgRB_din;

assign imgRB_write = grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_imgRB_write;

assign loopHeight_fu_227_p2 = (height_val4_dout + 11'd1);

assign loopWidth_fu_233_p2 = (width_val8_dout + 11'd1);

assign start_out = real_start;

assign trunc_ln630_fu_318_p1 = y_3_reg_467[0:0];

assign width_val8_c_din = width_val8_dout;

assign x_phase_fu_223_p1 = bayerPhase_val11_dout[0:0];

assign xor_i_fu_333_p2 = (trunc_ln_reg_461 ^ and310_cast_i_fu_329_p1);

assign y_4_fu_262_p2 = (y_fu_70 + 11'd1);

endmodule //design_1_v_demosaic_0_2_DebayerRatBorBatR
