#Camera 0
set_property PACKAGE_PIN AH14 [get_ports {cam_gpio_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_gpio_tri_io[0]}]
set_property PULLUP true [get_ports {cam_gpio_tri_io[0]}]

set_property PACKAGE_PIN AH13 [get_ports cam0_i2c_scl_io]
set_property PACKAGE_PIN AE13 [get_ports cam0_i2c_sda_io]

set_property IOSTANDARD LVCMOS33 [get_ports cam0_i2c_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports cam0_i2c_sda_io]

set_property PULLUP true [get_ports cam0_i2c_scl_io]
set_property PULLUP true [get_ports cam0_i2c_sda_io]


#Camera 1
set_property PACKAGE_PIN AD15 [get_ports {cam_gpio_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_gpio_tri_io[1]}]
set_property PULLUP true [get_ports {cam_gpio_tri_io[1]}]

set_property PACKAGE_PIN AD14 [get_ports cam1_i2c_scl_io]
set_property PACKAGE_PIN AC13 [get_ports cam1_i2c_sda_io]

set_property IOSTANDARD LVCMOS33 [get_ports cam1_i2c_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports cam1_i2c_sda_io]


set_property PULLUP true [get_ports cam1_i2c_scl_io]
set_property PULLUP true [get_ports cam1_i2c_sda_io]


set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[20]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[21]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[22]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[23]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[24]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[25]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[26]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[27]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[28]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[29]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[30]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[31]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[32]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[33]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[34]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[35]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[36]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[37]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[38]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[39]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[40]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[41]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[42]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[43]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[44]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[45]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[46]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[47]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[48]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[49]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[50]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[51]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[52]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[53]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[54]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[55]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[56]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[57]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[58]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[59]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[60]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[61]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[62]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[63]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[64]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[65]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[66]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[67]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[68]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[69]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[70]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[71]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[72]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[73]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[74]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[75]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[76]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[77]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[78]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[79]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[80]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[81]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[82]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[83]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[84]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[85]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[86]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[87]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[88]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[89]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[90]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[91]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[92]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[93]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_gpio_tri_io[94]}]