# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Dev/QianSai/mipi_dp_vivado/mipi_dp.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_1/ip_0/bd_d10d_phy_0_hssio_rx.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d10d_phy_0_hssio_rx || ORIG_REF_NAME==bd_d10d_phy_0_hssio_rx} -quiet] -quiet

# XDC: e:/Dev/QianSai/mipi_dp_vivado/mipi_dp.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_1/ip_0/bd_d10d_phy_0_hssio_rx.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d10d_phy_0_hssio_rx || ORIG_REF_NAME==bd_d10d_phy_0_hssio_rx} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/Dev/QianSai/mipi_dp_vivado/mipi_dp.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_1/ip_0/bd_d10d_phy_0_hssio_rx_ooc.xdc

# XDC: e:/Dev/QianSai/mipi_dp_vivado/mipi_dp.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_1/bd_d10d_phy_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d10d_phy_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Dev/QianSai/mipi_dp_vivado/mipi_dp.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_1/bd_d10d_phy_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d10d_phy_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Dev/QianSai/mipi_dp_vivado/mipi_dp.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_1/bd_d10d_phy_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d10d_phy_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/Dev/QianSai/mipi_dp_vivado/mipi_dp.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_1/ip_0/bd_d10d_phy_0_hssio_rx.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d10d_phy_0_hssio_rx || ORIG_REF_NAME==bd_d10d_phy_0_hssio_rx} -quiet] -quiet

# XDC: e:/Dev/QianSai/mipi_dp_vivado/mipi_dp.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_1/ip_0/bd_d10d_phy_0_hssio_rx.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d10d_phy_0_hssio_rx || ORIG_REF_NAME==bd_d10d_phy_0_hssio_rx} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/Dev/QianSai/mipi_dp_vivado/mipi_dp.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_1/ip_0/bd_d10d_phy_0_hssio_rx_ooc.xdc

# XDC: e:/Dev/QianSai/mipi_dp_vivado/mipi_dp.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_1/bd_d10d_phy_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d10d_phy_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Dev/QianSai/mipi_dp_vivado/mipi_dp.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_1/bd_d10d_phy_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d10d_phy_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Dev/QianSai/mipi_dp_vivado/mipi_dp.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_1/bd_d10d_phy_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d10d_phy_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
