-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity design_1_v_demosaic_1_0_DebayerRatBorBatR is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    imgG_dout : IN STD_LOGIC_VECTOR (29 downto 0);
    imgG_empty_n : IN STD_LOGIC;
    imgG_read : OUT STD_LOGIC;
    imgG_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    imgG_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    imgRB_din : OUT STD_LOGIC_VECTOR (29 downto 0);
    imgRB_full_n : IN STD_LOGIC;
    imgRB_write : OUT STD_LOGIC;
    imgRB_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    imgRB_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    height_val4_dout : IN STD_LOGIC_VECTOR (10 downto 0);
    height_val4_empty_n : IN STD_LOGIC;
    height_val4_read : OUT STD_LOGIC;
    height_val4_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    height_val4_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    width_val8_dout : IN STD_LOGIC_VECTOR (10 downto 0);
    width_val8_empty_n : IN STD_LOGIC;
    width_val8_read : OUT STD_LOGIC;
    width_val8_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    width_val8_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    bayerPhase_val11_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    bayerPhase_val11_empty_n : IN STD_LOGIC;
    bayerPhase_val11_read : OUT STD_LOGIC;
    bayerPhase_val11_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    bayerPhase_val11_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    height_val4_c_din : OUT STD_LOGIC_VECTOR (10 downto 0);
    height_val4_c_full_n : IN STD_LOGIC;
    height_val4_c_write : OUT STD_LOGIC;
    height_val4_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    height_val4_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    width_val8_c_din : OUT STD_LOGIC_VECTOR (10 downto 0);
    width_val8_c_full_n : IN STD_LOGIC;
    width_val8_c_write : OUT STD_LOGIC;
    width_val8_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    width_val8_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    bayerPhase_val11_c_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    bayerPhase_val11_c_full_n : IN STD_LOGIC;
    bayerPhase_val11_c_write : OUT STD_LOGIC;
    bayerPhase_val11_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    bayerPhase_val11_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of design_1_v_demosaic_1_0_DebayerRatBorBatR is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal height_val4_blk_n : STD_LOGIC;
    signal width_val8_blk_n : STD_LOGIC;
    signal bayerPhase_val11_blk_n : STD_LOGIC;
    signal height_val4_c_blk_n : STD_LOGIC;
    signal width_val8_c_blk_n : STD_LOGIC;
    signal bayerPhase_val11_c_blk_n : STD_LOGIC;
    signal width_val8_read_reg_436 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal height_val4_read_reg_441 : STD_LOGIC_VECTOR (10 downto 0);
    signal x_phase_fu_223_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_phase_reg_446 : STD_LOGIC_VECTOR (0 downto 0);
    signal loopHeight_fu_227_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal loopHeight_reg_451 : STD_LOGIC_VECTOR (10 downto 0);
    signal loopWidth_fu_233_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal loopWidth_reg_456 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln_reg_461 : STD_LOGIC_VECTOR (14 downto 0);
    signal y_3_reg_467 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal p_0_0_09411390_lcssa1442_i_load_reg_476 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_09401393_lcssa1444_i_load_reg_481 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_09391396_lcssa1446_i_load_reg_486 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0941_21420_lcssa1454_i_load_reg_491 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0940_21423_lcssa1456_i_load_reg_496 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0939_21426_lcssa1458_i_load_reg_501 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0_0_09141487_lcssa1524_i_load_reg_506 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_1_0_0_09151489_lcssa1526_i_load_reg_511 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_2_0_0_09161491_lcssa1528_i_load_reg_516 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0941_114821494_lcssa1530_i_load_reg_521 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0940_114841496_lcssa1532_i_load_reg_526 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0939_114861498_lcssa1534_i_load_reg_531 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0_0_09081499_lcssa1536_i_load_reg_536 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_1_0_0_09091501_lcssa1538_i_load_reg_541 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_2_0_0_09101503_lcssa1540_i_load_reg_546 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln630_fu_318_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln630_reg_551 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal and310_i_fu_322_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and310_i_reg_556 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_i_fu_333_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal xor_i_reg_561 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_start : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_done : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_idle : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_ready : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_imgG_read : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_imgRB_din : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_imgRB_write : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_2_0_0_09101504_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_2_0_0_09101504_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_1_0_0_09091502_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_1_0_0_09091502_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0_0_09081500_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0_0_09081500_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0939_114861497_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0939_114861497_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0940_114841495_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0940_114841495_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0941_114821493_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0941_114821493_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_2_0_0_09161492_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_2_0_0_09161492_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_1_0_0_09151490_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_1_0_0_09151490_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0_0_09141488_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0_0_09141488_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0939_21425_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0939_21425_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0940_21422_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0940_21422_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0941_21419_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0941_21419_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09391395_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09391395_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09401392_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09401392_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09411389_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09411389_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal p_0_2_0_0_09101503_lcssa1540_i_fu_130 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_1_0_0_09091501_lcssa1538_i_fu_126 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0_0_09081499_lcssa1536_i_fu_122 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0939_114861498_lcssa1534_i_fu_118 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0940_114841496_lcssa1532_i_fu_114 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0941_114821494_lcssa1530_i_fu_110 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_2_0_0_09161491_lcssa1528_i_fu_106 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_1_0_0_09151489_lcssa1526_i_fu_102 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0_0_09141487_lcssa1524_i_fu_98 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0939_21426_lcssa1458_i_fu_94 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0940_21423_lcssa1456_i_fu_90 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0941_21420_lcssa1454_i_fu_86 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_09391396_lcssa1446_i_fu_82 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_09401393_lcssa1444_i_fu_78 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_09411390_lcssa1442_i_fu_74 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_fu_70 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal y_4_fu_262_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln630_fu_257_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and310_cast_i_fu_329_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component design_1_v_demosaic_1_0_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        imgG_dout : IN STD_LOGIC_VECTOR (29 downto 0);
        imgG_empty_n : IN STD_LOGIC;
        imgG_read : OUT STD_LOGIC;
        imgG_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        imgG_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        imgRB_din : OUT STD_LOGIC_VECTOR (29 downto 0);
        imgRB_full_n : IN STD_LOGIC;
        imgRB_write : OUT STD_LOGIC;
        imgRB_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        imgRB_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
        p_0_2_0_0_09101503_lcssa1540_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_1_0_0_09091501_lcssa1538_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0_0_09081499_lcssa1536_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0939_114861498_lcssa1534_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0940_114841496_lcssa1532_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0941_114821494_lcssa1530_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_2_0_0_09161491_lcssa1528_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_1_0_0_09151489_lcssa1526_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0_0_09141487_lcssa1524_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0939_21426_lcssa1458_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0940_21423_lcssa1456_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0941_21420_lcssa1454_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_09391396_lcssa1446_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_09401393_lcssa1444_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_09411390_lcssa1442_i : IN STD_LOGIC_VECTOR (9 downto 0);
        loopWidth : IN STD_LOGIC_VECTOR (10 downto 0);
        empty_58 : IN STD_LOGIC_VECTOR (0 downto 0);
        xor_i : IN STD_LOGIC_VECTOR (14 downto 0);
        width_val8_load : IN STD_LOGIC_VECTOR (10 downto 0);
        and310_cast_i : IN STD_LOGIC_VECTOR (0 downto 0);
        trunc_ln : IN STD_LOGIC_VECTOR (14 downto 0);
        empty : IN STD_LOGIC_VECTOR (0 downto 0);
        y : IN STD_LOGIC_VECTOR (10 downto 0);
        height_val4_load : IN STD_LOGIC_VECTOR (10 downto 0);
        p_0_2_0_0_09101504_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_2_0_0_09101504_i_out_ap_vld : OUT STD_LOGIC;
        p_0_1_0_0_09091502_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_1_0_0_09091502_i_out_ap_vld : OUT STD_LOGIC;
        p_0_0_0_0_09081500_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0_0_09081500_i_out_ap_vld : OUT STD_LOGIC;
        p_0_0_0939_114861497_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0939_114861497_i_out_ap_vld : OUT STD_LOGIC;
        p_0_0_0940_114841495_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0940_114841495_i_out_ap_vld : OUT STD_LOGIC;
        p_0_0_0941_114821493_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0941_114821493_i_out_ap_vld : OUT STD_LOGIC;
        p_0_2_0_0_09161492_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_2_0_0_09161492_i_out_ap_vld : OUT STD_LOGIC;
        p_0_1_0_0_09151490_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_1_0_0_09151490_i_out_ap_vld : OUT STD_LOGIC;
        p_0_0_0_0_09141488_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0_0_09141488_i_out_ap_vld : OUT STD_LOGIC;
        p_0_0_0939_21425_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0939_21425_i_out_ap_vld : OUT STD_LOGIC;
        p_0_0_0940_21422_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0940_21422_i_out_ap_vld : OUT STD_LOGIC;
        p_0_0_0941_21419_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0941_21419_i_out_ap_vld : OUT STD_LOGIC;
        p_0_0_09391395_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_09391395_i_out_ap_vld : OUT STD_LOGIC;
        p_0_0_09401392_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_09401392_i_out_ap_vld : OUT STD_LOGIC;
        p_0_0_09411389_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_09411389_i_out_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176 : component design_1_v_demosaic_1_0_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_start,
        ap_done => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_done,
        ap_idle => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_idle,
        ap_ready => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_ready,
        imgG_dout => imgG_dout,
        imgG_empty_n => imgG_empty_n,
        imgG_read => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_imgG_read,
        imgG_num_data_valid => ap_const_lv3_0,
        imgG_fifo_cap => ap_const_lv3_0,
        imgRB_din => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_imgRB_din,
        imgRB_full_n => imgRB_full_n,
        imgRB_write => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_imgRB_write,
        imgRB_num_data_valid => imgRB_num_data_valid,
        imgRB_fifo_cap => imgRB_fifo_cap,
        p_0_2_0_0_09101503_lcssa1540_i => p_0_2_0_0_09101503_lcssa1540_i_load_reg_546,
        p_0_1_0_0_09091501_lcssa1538_i => p_0_1_0_0_09091501_lcssa1538_i_load_reg_541,
        p_0_0_0_0_09081499_lcssa1536_i => p_0_0_0_0_09081499_lcssa1536_i_load_reg_536,
        p_0_0_0939_114861498_lcssa1534_i => p_0_0_0939_114861498_lcssa1534_i_load_reg_531,
        p_0_0_0940_114841496_lcssa1532_i => p_0_0_0940_114841496_lcssa1532_i_load_reg_526,
        p_0_0_0941_114821494_lcssa1530_i => p_0_0_0941_114821494_lcssa1530_i_load_reg_521,
        p_0_2_0_0_09161491_lcssa1528_i => p_0_2_0_0_09161491_lcssa1528_i_load_reg_516,
        p_0_1_0_0_09151489_lcssa1526_i => p_0_1_0_0_09151489_lcssa1526_i_load_reg_511,
        p_0_0_0_0_09141487_lcssa1524_i => p_0_0_0_0_09141487_lcssa1524_i_load_reg_506,
        p_0_0_0939_21426_lcssa1458_i => p_0_0_0939_21426_lcssa1458_i_load_reg_501,
        p_0_0_0940_21423_lcssa1456_i => p_0_0_0940_21423_lcssa1456_i_load_reg_496,
        p_0_0_0941_21420_lcssa1454_i => p_0_0_0941_21420_lcssa1454_i_load_reg_491,
        p_0_0_09391396_lcssa1446_i => p_0_0_09391396_lcssa1446_i_load_reg_486,
        p_0_0_09401393_lcssa1444_i => p_0_0_09401393_lcssa1444_i_load_reg_481,
        p_0_0_09411390_lcssa1442_i => p_0_0_09411390_lcssa1442_i_load_reg_476,
        loopWidth => loopWidth_reg_456,
        empty_58 => x_phase_reg_446,
        xor_i => xor_i_reg_561,
        width_val8_load => width_val8_read_reg_436,
        and310_cast_i => and310_i_reg_556,
        trunc_ln => trunc_ln_reg_461,
        empty => trunc_ln630_reg_551,
        y => y_3_reg_467,
        height_val4_load => height_val4_read_reg_441,
        p_0_2_0_0_09101504_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_2_0_0_09101504_i_out,
        p_0_2_0_0_09101504_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_2_0_0_09101504_i_out_ap_vld,
        p_0_1_0_0_09091502_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_1_0_0_09091502_i_out,
        p_0_1_0_0_09091502_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_1_0_0_09091502_i_out_ap_vld,
        p_0_0_0_0_09081500_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0_0_09081500_i_out,
        p_0_0_0_0_09081500_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0_0_09081500_i_out_ap_vld,
        p_0_0_0939_114861497_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0939_114861497_i_out,
        p_0_0_0939_114861497_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0939_114861497_i_out_ap_vld,
        p_0_0_0940_114841495_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0940_114841495_i_out,
        p_0_0_0940_114841495_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0940_114841495_i_out_ap_vld,
        p_0_0_0941_114821493_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0941_114821493_i_out,
        p_0_0_0941_114821493_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0941_114821493_i_out_ap_vld,
        p_0_2_0_0_09161492_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_2_0_0_09161492_i_out,
        p_0_2_0_0_09161492_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_2_0_0_09161492_i_out_ap_vld,
        p_0_1_0_0_09151490_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_1_0_0_09151490_i_out,
        p_0_1_0_0_09151490_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_1_0_0_09151490_i_out_ap_vld,
        p_0_0_0_0_09141488_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0_0_09141488_i_out,
        p_0_0_0_0_09141488_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0_0_09141488_i_out_ap_vld,
        p_0_0_0939_21425_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0939_21425_i_out,
        p_0_0_0939_21425_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0939_21425_i_out_ap_vld,
        p_0_0_0940_21422_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0940_21422_i_out,
        p_0_0_0940_21422_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0940_21422_i_out_ap_vld,
        p_0_0_0941_21419_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0941_21419_i_out,
        p_0_0_0941_21419_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0941_21419_i_out_ap_vld,
        p_0_0_09391395_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09391395_i_out,
        p_0_0_09391395_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09391395_i_out_ap_vld,
        p_0_0_09401392_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09401392_i_out,
        p_0_0_09401392_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09401392_i_out_ap_vld,
        p_0_0_09411389_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09411389_i_out,
        p_0_0_09411389_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09411389_i_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln630_fu_257_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_ready = ap_const_logic_1)) then 
                    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    y_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                y_fu_70 <= ap_const_lv11_0;
            elsif (((icmp_ln630_fu_257_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                y_fu_70 <= y_4_fu_262_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                and310_i_reg_556 <= and310_i_fu_322_p2;
                trunc_ln630_reg_551 <= trunc_ln630_fu_318_p1;
                xor_i_reg_561 <= xor_i_fu_333_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                height_val4_read_reg_441 <= height_val4_dout;
                loopHeight_reg_451 <= loopHeight_fu_227_p2;
                loopWidth_reg_456 <= loopWidth_fu_233_p2;
                trunc_ln_reg_461 <= bayerPhase_val11_dout(15 downto 1);
                width_val8_read_reg_436 <= width_val8_dout;
                x_phase_reg_446 <= x_phase_fu_223_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09391395_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_09391396_lcssa1446_i_fu_82 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09391395_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                p_0_0_09391396_lcssa1446_i_load_reg_486 <= p_0_0_09391396_lcssa1446_i_fu_82;
                p_0_0_0939_114861498_lcssa1534_i_load_reg_531 <= p_0_0_0939_114861498_lcssa1534_i_fu_118;
                p_0_0_0939_21426_lcssa1458_i_load_reg_501 <= p_0_0_0939_21426_lcssa1458_i_fu_94;
                p_0_0_09401393_lcssa1444_i_load_reg_481 <= p_0_0_09401393_lcssa1444_i_fu_78;
                p_0_0_0940_114841496_lcssa1532_i_load_reg_526 <= p_0_0_0940_114841496_lcssa1532_i_fu_114;
                p_0_0_0940_21423_lcssa1456_i_load_reg_496 <= p_0_0_0940_21423_lcssa1456_i_fu_90;
                p_0_0_09411390_lcssa1442_i_load_reg_476 <= p_0_0_09411390_lcssa1442_i_fu_74;
                p_0_0_0941_114821494_lcssa1530_i_load_reg_521 <= p_0_0_0941_114821494_lcssa1530_i_fu_110;
                p_0_0_0941_21420_lcssa1454_i_load_reg_491 <= p_0_0_0941_21420_lcssa1454_i_fu_86;
                p_0_0_0_0_09081499_lcssa1536_i_load_reg_536 <= p_0_0_0_0_09081499_lcssa1536_i_fu_122;
                p_0_0_0_0_09141487_lcssa1524_i_load_reg_506 <= p_0_0_0_0_09141487_lcssa1524_i_fu_98;
                p_0_1_0_0_09091501_lcssa1538_i_load_reg_541 <= p_0_1_0_0_09091501_lcssa1538_i_fu_126;
                p_0_1_0_0_09151489_lcssa1526_i_load_reg_511 <= p_0_1_0_0_09151489_lcssa1526_i_fu_102;
                p_0_2_0_0_09101503_lcssa1540_i_load_reg_546 <= p_0_2_0_0_09101503_lcssa1540_i_fu_130;
                p_0_2_0_0_09161491_lcssa1528_i_load_reg_516 <= p_0_2_0_0_09161491_lcssa1528_i_fu_106;
                y_3_reg_467 <= y_fu_70;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0939_114861497_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_0939_114861498_lcssa1534_i_fu_118 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0939_114861497_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0939_21425_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_0939_21426_lcssa1458_i_fu_94 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0939_21425_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09401392_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_09401393_lcssa1444_i_fu_78 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09401392_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0940_114841495_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_0940_114841496_lcssa1532_i_fu_114 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0940_114841495_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0940_21422_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_0940_21423_lcssa1456_i_fu_90 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0940_21422_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09411389_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_09411390_lcssa1442_i_fu_74 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_09411389_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0941_114821493_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_0941_114821494_lcssa1530_i_fu_110 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0941_114821493_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0941_21419_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_0941_21420_lcssa1454_i_fu_86 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0941_21419_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0_0_09081500_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_0_0_09081499_lcssa1536_i_fu_122 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0_0_09081500_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0_0_09141488_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_0_0_09141487_lcssa1524_i_fu_98 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_0_0_0_09141488_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_1_0_0_09091502_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_1_0_0_09091501_lcssa1538_i_fu_126 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_1_0_0_09091502_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_1_0_0_09151490_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_1_0_0_09151489_lcssa1526_i_fu_102 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_1_0_0_09151490_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_2_0_0_09101504_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_2_0_0_09101503_lcssa1540_i_fu_130 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_2_0_0_09101504_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_2_0_0_09161492_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_2_0_0_09161491_lcssa1528_i_fu_106 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_p_0_2_0_0_09161492_i_out;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state2, grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_done, ap_CS_fsm_state4, icmp_ln630_fu_257_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln630_fu_257_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    and310_cast_i_fu_329_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and310_i_fu_322_p2),15));
    and310_i_fu_322_p2 <= (trunc_ln630_fu_318_p1 xor ap_const_lv1_1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_done)
    begin
        if ((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, height_val4_empty_n, width_val8_empty_n, bayerPhase_val11_empty_n, height_val4_c_full_n, width_val8_c_full_n, bayerPhase_val11_c_full_n)
    begin
                ap_block_state1 <= ((bayerPhase_val11_c_full_n = ap_const_logic_0) or (width_val8_c_full_n = ap_const_logic_0) or (height_val4_c_full_n = ap_const_logic_0) or (bayerPhase_val11_empty_n = ap_const_logic_0) or (width_val8_empty_n = ap_const_logic_0) or (height_val4_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln630_fu_257_p2)
    begin
        if (((icmp_ln630_fu_257_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    bayerPhase_val11_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, bayerPhase_val11_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            bayerPhase_val11_blk_n <= bayerPhase_val11_empty_n;
        else 
            bayerPhase_val11_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    bayerPhase_val11_c_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, bayerPhase_val11_c_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            bayerPhase_val11_c_blk_n <= bayerPhase_val11_c_full_n;
        else 
            bayerPhase_val11_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    bayerPhase_val11_c_din <= bayerPhase_val11_dout;

    bayerPhase_val11_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            bayerPhase_val11_c_write <= ap_const_logic_1;
        else 
            bayerPhase_val11_c_write <= ap_const_logic_0;
        end if; 
    end process;


    bayerPhase_val11_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            bayerPhase_val11_read <= ap_const_logic_1;
        else 
            bayerPhase_val11_read <= ap_const_logic_0;
        end if; 
    end process;

    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_start <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_ap_start_reg;

    height_val4_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, height_val4_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            height_val4_blk_n <= height_val4_empty_n;
        else 
            height_val4_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    height_val4_c_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, height_val4_c_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            height_val4_c_blk_n <= height_val4_c_full_n;
        else 
            height_val4_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    height_val4_c_din <= height_val4_dout;

    height_val4_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            height_val4_c_write <= ap_const_logic_1;
        else 
            height_val4_c_write <= ap_const_logic_0;
        end if; 
    end process;


    height_val4_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            height_val4_read <= ap_const_logic_1;
        else 
            height_val4_read <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln630_fu_257_p2 <= "1" when (y_fu_70 = loopHeight_reg_451) else "0";
    imgG_read <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_imgG_read;
    imgRB_din <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_imgRB_din;
    imgRB_write <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_176_imgRB_write;

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln630_fu_257_p2)
    begin
        if (((icmp_ln630_fu_257_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    loopHeight_fu_227_p2 <= std_logic_vector(unsigned(height_val4_dout) + unsigned(ap_const_lv11_1));
    loopWidth_fu_233_p2 <= std_logic_vector(unsigned(width_val8_dout) + unsigned(ap_const_lv11_1));

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln630_fu_318_p1 <= y_3_reg_467(1 - 1 downto 0);

    width_val8_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, width_val8_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            width_val8_blk_n <= width_val8_empty_n;
        else 
            width_val8_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    width_val8_c_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, width_val8_c_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            width_val8_c_blk_n <= width_val8_c_full_n;
        else 
            width_val8_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    width_val8_c_din <= width_val8_dout;

    width_val8_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            width_val8_c_write <= ap_const_logic_1;
        else 
            width_val8_c_write <= ap_const_logic_0;
        end if; 
    end process;


    width_val8_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            width_val8_read <= ap_const_logic_1;
        else 
            width_val8_read <= ap_const_logic_0;
        end if; 
    end process;

    x_phase_fu_223_p1 <= bayerPhase_val11_dout(1 - 1 downto 0);
    xor_i_fu_333_p2 <= (trunc_ln_reg_461 xor and310_cast_i_fu_329_p1);
    y_4_fu_262_p2 <= std_logic_vector(unsigned(y_fu_70) + unsigned(ap_const_lv11_1));
end behav;
