// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module design_1_v_demosaic_0_2_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        imgRB_dout,
        imgRB_empty_n,
        imgRB_read,
        imgRB_num_data_valid,
        imgRB_fifo_cap,
        imgRgb_din,
        imgRgb_full_n,
        imgRgb_write,
        imgRgb_num_data_valid,
        imgRgb_fifo_cap,
        p_0_0_01174_217341764_lcssa1800_i,
        p_0_0_01175_217321762_lcssa1798_i,
        p_0_0_01176_217301760_lcssa1796_i,
        p_0_2_0_0_011511757_lcssa1794_i,
        p_0_1_0_0_011501755_lcssa1792_i,
        p_0_0_0_0_011491753_lcssa1790_i,
        p_0_0_0116117401752_lcssa1788_i,
        p_0_0_0116217381750_lcssa1786_i,
        p_0_0_0116317361748_lcssa1784_i,
        p_0_2_0_0_011571664_lcssa1706_i,
        p_0_1_0_0_011561661_lcssa1704_i,
        p_0_0_0_0_011551658_lcssa1702_i,
        loopWidth,
        empty,
        xor_i,
        width_val8_load,
        y,
        height_val4_load,
        p_0_0_01174_217341763_i_out,
        p_0_0_01174_217341763_i_out_ap_vld,
        p_0_0_01175_217321761_i_out,
        p_0_0_01175_217321761_i_out_ap_vld,
        p_0_0_01176_217301759_i_out,
        p_0_0_01176_217301759_i_out_ap_vld,
        right_2_out,
        right_2_out_ap_vld,
        right_1_out,
        right_1_out_ap_vld,
        right_out,
        right_out_ap_vld,
        p_0_0_0116117401751_i_out,
        p_0_0_0116117401751_i_out_ap_vld,
        p_0_0_0116217381749_i_out,
        p_0_0_0116217381749_i_out_ap_vld,
        p_0_0_0116317361747_i_out,
        p_0_0_0116317361747_i_out_ap_vld,
        p_0_2_0_0_011571666_i_out,
        p_0_2_0_0_011571666_i_out_ap_vld,
        p_0_1_0_0_011561663_i_out,
        p_0_1_0_0_011561663_i_out_ap_vld,
        p_0_0_0_0_011551660_i_out,
        p_0_0_0_0_011551660_i_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [29:0] imgRB_dout;
input   imgRB_empty_n;
output   imgRB_read;
input  [2:0] imgRB_num_data_valid;
input  [2:0] imgRB_fifo_cap;
output  [29:0] imgRgb_din;
input   imgRgb_full_n;
output   imgRgb_write;
input  [31:0] imgRgb_num_data_valid;
input  [31:0] imgRgb_fifo_cap;
input  [9:0] p_0_0_01174_217341764_lcssa1800_i;
input  [9:0] p_0_0_01175_217321762_lcssa1798_i;
input  [9:0] p_0_0_01176_217301760_lcssa1796_i;
input  [9:0] p_0_2_0_0_011511757_lcssa1794_i;
input  [9:0] p_0_1_0_0_011501755_lcssa1792_i;
input  [9:0] p_0_0_0_0_011491753_lcssa1790_i;
input  [9:0] p_0_0_0116117401752_lcssa1788_i;
input  [9:0] p_0_0_0116217381750_lcssa1786_i;
input  [9:0] p_0_0_0116317361748_lcssa1784_i;
input  [9:0] p_0_2_0_0_011571664_lcssa1706_i;
input  [9:0] p_0_1_0_0_011561661_lcssa1704_i;
input  [9:0] p_0_0_0_0_011551658_lcssa1702_i;
input  [10:0] loopWidth;
input  [0:0] empty;
input  [14:0] xor_i;
input  [10:0] width_val8_load;
input  [10:0] y;
input  [10:0] height_val4_load;
output  [9:0] p_0_0_01174_217341763_i_out;
output   p_0_0_01174_217341763_i_out_ap_vld;
output  [9:0] p_0_0_01175_217321761_i_out;
output   p_0_0_01175_217321761_i_out_ap_vld;
output  [9:0] p_0_0_01176_217301759_i_out;
output   p_0_0_01176_217301759_i_out_ap_vld;
output  [9:0] right_2_out;
output   right_2_out_ap_vld;
output  [9:0] right_1_out;
output   right_1_out_ap_vld;
output  [9:0] right_out;
output   right_out_ap_vld;
output  [9:0] p_0_0_0116117401751_i_out;
output   p_0_0_0116117401751_i_out_ap_vld;
output  [9:0] p_0_0_0116217381749_i_out;
output   p_0_0_0116217381749_i_out_ap_vld;
output  [9:0] p_0_0_0116317361747_i_out;
output   p_0_0_0116317361747_i_out_ap_vld;
output  [9:0] p_0_2_0_0_011571666_i_out;
output   p_0_2_0_0_011571666_i_out_ap_vld;
output  [9:0] p_0_1_0_0_011561663_i_out;
output   p_0_1_0_0_011561663_i_out_ap_vld;
output  [9:0] p_0_0_0_0_011551660_i_out;
output   p_0_0_0_0_011551660_i_out_ap_vld;

reg ap_idle;
reg imgRB_read;
reg imgRgb_write;
reg p_0_0_01174_217341763_i_out_ap_vld;
reg p_0_0_01175_217321761_i_out_ap_vld;
reg p_0_0_01176_217301759_i_out_ap_vld;
reg right_2_out_ap_vld;
reg right_1_out_ap_vld;
reg right_out_ap_vld;
reg p_0_0_0116117401751_i_out_ap_vld;
reg p_0_0_0116217381749_i_out_ap_vld;
reg p_0_0_0116317361747_i_out_ap_vld;
reg p_0_2_0_0_011571666_i_out_ap_vld;
reg p_0_1_0_0_011561663_i_out_ap_vld;
reg p_0_0_0_0_011551660_i_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln881_reg_1974;
reg   [0:0] icmp_ln891_reg_1978;
reg   [0:0] cmp59_i_reg_1965;
reg    ap_predicate_op103_read_state2;
reg    ap_block_state2_pp0_stage0_iter1;
reg   [0:0] and_ln1052_reg_2016;
reg   [0:0] and_ln1052_reg_2016_pp0_iter2_reg;
reg    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln881_fu_594_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    imgRB_blk_n;
wire    ap_block_pp0_stage0;
reg    imgRgb_blk_n;
reg   [9:0] pix_8_reg_403;
reg   [9:0] pix_8_reg_403_pp0_iter2_reg;
reg    ap_block_pp0_stage0_11001;
reg   [9:0] pix_7_reg_413;
reg   [9:0] pix_7_reg_413_pp0_iter2_reg;
reg   [9:0] pix_reg_423;
reg   [9:0] pix_reg_423_pp0_iter2_reg;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
wire   [0:0] cmp59_i_fu_514_p2;
wire   [0:0] cmp203_i_fu_520_p2;
reg   [0:0] cmp203_i_reg_1969;
reg   [0:0] icmp_ln881_reg_1974_pp0_iter1_reg;
wire   [0:0] icmp_ln891_fu_616_p2;
reg   [10:0] lineBuffer_addr_reg_1982;
reg   [10:0] lineBuffer_2_addr_reg_1988;
wire   [0:0] cmp161_i_fu_622_p2;
reg   [0:0] cmp161_i_reg_1994;
wire   [0:0] icmp_ln1014_fu_644_p2;
reg   [0:0] icmp_ln1014_reg_2010;
reg   [0:0] icmp_ln1014_reg_2010_pp0_iter1_reg;
reg   [0:0] icmp_ln1014_reg_2010_pp0_iter2_reg;
wire   [0:0] and_ln1052_fu_656_p2;
reg   [0:0] and_ln1052_reg_2016_pp0_iter1_reg;
reg   [9:0] p_0_0_0116317361747_i_load_reg_2020;
reg   [9:0] p_0_0_0116217381749_i_load_reg_2026;
reg   [9:0] p_0_0_0116117401751_i_load_reg_2032;
reg   [9:0] right_3_reg_2038;
reg   [9:0] right_4_reg_2043;
reg   [9:0] right_5_reg_2048;
reg   [9:0] p_0_0_01176_217301759_i_load_reg_2053;
reg   [9:0] p_0_0_01175_217321761_i_load_reg_2059;
reg   [9:0] p_0_0_01174_217341763_i_load_reg_2065;
reg   [9:0] p_0_0_0_0_011551660_i_load_reg_2071;
reg   [9:0] p_0_1_0_0_011561663_i_load_reg_2077;
reg   [9:0] p_0_2_0_0_011571666_i_load_reg_2083;
wire   [9:0] select_ln957_3_fu_800_p3;
wire   [9:0] select_ln957_4_fu_807_p3;
wire   [9:0] select_ln957_5_fu_814_p3;
wire   [9:0] select_ln957_6_fu_821_p3;
wire   [9:0] select_ln957_7_fu_828_p3;
wire   [9:0] select_ln957_8_fu_835_p3;
wire   [9:0] select_ln957_9_fu_842_p3;
wire   [9:0] select_ln957_10_fu_849_p3;
wire   [9:0] select_ln957_11_fu_856_p3;
wire   [0:0] icmp_ln1030_fu_1318_p2;
reg   [0:0] icmp_ln1030_reg_2134;
wire  signed [11:0] add_ln1033_fu_1344_p2;
reg  signed [11:0] add_ln1033_reg_2140;
wire   [10:0] sub_ln1033_3_fu_1370_p2;
reg   [10:0] sub_ln1033_3_reg_2146;
wire  signed [11:0] add_ln1034_fu_1396_p2;
reg  signed [11:0] add_ln1034_reg_2151;
wire   [10:0] sub_ln1034_3_fu_1422_p2;
reg   [10:0] sub_ln1034_3_reg_2157;
wire   [10:0] select_ln1039_fu_1498_p3;
reg   [10:0] select_ln1039_reg_2162;
wire   [10:0] select_ln1040_fu_1576_p3;
reg   [10:0] select_ln1040_reg_2167;
reg    ap_condition_exit_pp0_iter1_stage0;
wire   [10:0] lineBuffer_2_address0;
wire   [10:0] lineBuffer_2_address1;
wire   [29:0] lineBuffer_2_q1;
wire   [10:0] lineBuffer_address0;
wire   [10:0] lineBuffer_address1;
wire   [29:0] lineBuffer_q1;
reg   [9:0] ap_phi_mux_p_0_0_01174_21734_ph_i_phi_fu_379_p4;
wire   [9:0] ap_phi_reg_pp0_iter1_p_0_0_01174_21734_ph_i_reg_376;
wire   [9:0] tmp_1_i_fu_720_p3;
reg   [9:0] ap_phi_mux_p_0_0_01175_21732_ph_i_phi_fu_388_p4;
wire   [9:0] ap_phi_reg_pp0_iter1_p_0_0_01175_21732_ph_i_reg_385;
wire   [9:0] tmp_i_fu_711_p3;
reg   [9:0] ap_phi_mux_p_0_0_01176_21730_ph_i_phi_fu_397_p4;
wire   [9:0] trunc_ln913_fu_749_p1;
wire   [9:0] ap_phi_reg_pp0_iter1_p_0_0_01176_21730_ph_i_reg_394;
wire   [9:0] trunc_ln902_fu_706_p1;
reg   [9:0] ap_phi_mux_pix_8_phi_fu_406_p4;
wire   [9:0] select_ln957_2_fu_792_p3;
wire   [9:0] ap_phi_reg_pp0_iter1_pix_8_reg_403;
reg   [9:0] ap_phi_mux_pix_7_phi_fu_416_p4;
wire   [9:0] select_ln957_1_fu_784_p3;
wire   [9:0] ap_phi_reg_pp0_iter1_pix_7_reg_413;
reg   [9:0] ap_phi_mux_pix_phi_fu_426_p4;
wire   [9:0] select_ln957_fu_776_p3;
wire   [9:0] ap_phi_reg_pp0_iter1_pix_reg_423;
wire   [9:0] ap_phi_reg_pp0_iter0_down_2_reg_433;
reg   [9:0] ap_phi_reg_pp0_iter1_down_2_reg_433;
reg   [9:0] ap_phi_reg_pp0_iter2_down_2_reg_433;
wire   [9:0] ap_phi_reg_pp0_iter0_down_1_reg_442;
reg   [9:0] ap_phi_reg_pp0_iter1_down_1_reg_442;
reg   [9:0] ap_phi_reg_pp0_iter2_down_1_reg_442;
wire   [9:0] ap_phi_reg_pp0_iter0_down_reg_451;
reg   [9:0] ap_phi_reg_pp0_iter1_down_reg_451;
reg   [9:0] ap_phi_reg_pp0_iter2_down_reg_451;
wire   [9:0] ap_phi_reg_pp0_iter0_left_2_reg_460;
reg   [9:0] ap_phi_reg_pp0_iter1_left_2_reg_460;
reg   [9:0] ap_phi_reg_pp0_iter2_left_2_reg_460;
wire   [9:0] ap_phi_reg_pp0_iter0_left_1_reg_469;
reg   [9:0] ap_phi_reg_pp0_iter1_left_1_reg_469;
reg   [9:0] ap_phi_reg_pp0_iter2_left_1_reg_469;
wire   [9:0] ap_phi_reg_pp0_iter0_left_reg_478;
reg   [9:0] ap_phi_reg_pp0_iter1_left_reg_478;
reg   [9:0] ap_phi_reg_pp0_iter2_left_reg_478;
wire   [9:0] ap_phi_reg_pp0_iter0_up_2_reg_487;
reg   [9:0] ap_phi_reg_pp0_iter1_up_2_reg_487;
reg   [9:0] ap_phi_reg_pp0_iter2_up_2_reg_487;
wire   [9:0] ap_phi_reg_pp0_iter0_up_1_reg_496;
reg   [9:0] ap_phi_reg_pp0_iter1_up_1_reg_496;
reg   [9:0] ap_phi_reg_pp0_iter2_up_1_reg_496;
wire   [9:0] ap_phi_reg_pp0_iter0_up_reg_505;
reg   [9:0] ap_phi_reg_pp0_iter1_up_reg_505;
reg   [9:0] ap_phi_reg_pp0_iter2_up_reg_505;
wire   [63:0] zext_ln881_fu_610_p1;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
wire    ap_block_pp0_stage0_grp0;
reg   [10:0] x_fu_160;
wire   [10:0] x_8_fu_600_p2;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_z;
reg   [9:0] p_0_0_0116317361747_i_fu_164;
wire   [9:0] trunc_ln902_1_fu_729_p1;
reg   [9:0] p_0_0_0116217381749_i_fu_168;
wire   [9:0] tmp_3_i_fu_733_p3;
reg   [9:0] p_0_0_0116117401751_i_fu_172;
wire   [9:0] tmp_4_i_fu_741_p3;
reg   [9:0] right_fu_176;
reg   [9:0] right_1_fu_180;
reg   [9:0] right_2_fu_184;
reg   [9:0] p_0_0_01176_217301759_i_fu_188;
reg   [9:0] p_0_0_01175_217321761_i_fu_192;
reg   [9:0] p_0_0_01174_217341763_i_fu_196;
reg   [9:0] p_0_0_0_0_011551660_i_fu_200;
reg   [9:0] p_0_1_0_0_011561663_i_fu_204;
reg   [9:0] p_0_2_0_0_011571666_i_fu_208;
reg    ap_block_pp0_stage0_01001;
reg    lineBuffer_ce1_local;
reg    lineBuffer_we0_local;
reg    lineBuffer_ce0_local;
reg    lineBuffer_2_ce1_local;
reg    lineBuffer_2_we0_local;
wire   [29:0] LineBufVal_4_fu_942_p4;
reg    lineBuffer_2_ce0_local;
wire   [0:0] trunc_ln881_fu_606_p1;
wire   [0:0] xor_ln1014_fu_628_p2;
wire   [0:0] xor_ln1014_1_fu_634_p2;
wire   [14:0] zext_ln1014_fu_640_p1;
wire   [0:0] icmp_ln1052_fu_650_p2;
wire   [9:0] tmp_18_i_fu_887_p4;
wire   [9:0] tmp_17_i_fu_877_p4;
wire   [41:0] tmp_19_i_fu_897_p6;
wire   [41:0] tmp_2_fu_863_p6;
wire   [41:0] storemerge_1_in_i_fu_911_p3;
wire   [9:0] tmp_6_i_fu_932_p4;
wire   [9:0] tmp_5_i_fu_922_p4;
wire   [9:0] empty_154_fu_918_p1;
wire   [10:0] zext_ln1023_fu_1022_p1;
wire   [10:0] zext_ln1023_1_fu_1026_p1;
wire   [10:0] sub_ln1023_fu_1030_p2;
wire   [9:0] trunc_ln61_fu_1036_p1;
wire   [0:0] tmp_11_fu_1046_p3;
wire   [9:0] sub_ln61_fu_1040_p2;
wire   [10:0] zext_ln1024_fu_1062_p1;
wire   [10:0] zext_ln1024_1_fu_1066_p1;
wire   [10:0] sub_ln1024_fu_1070_p2;
wire   [9:0] trunc_ln61_4_fu_1076_p1;
wire   [0:0] tmp_12_fu_1086_p3;
wire   [9:0] sub_ln61_4_fu_1080_p2;
wire   [10:0] zext_ln1025_fu_1102_p1;
wire   [10:0] zext_ln1025_1_fu_1106_p1;
wire   [10:0] sub_ln1025_fu_1110_p2;
wire   [9:0] trunc_ln61_5_fu_1116_p1;
wire   [0:0] tmp_13_fu_1126_p3;
wire   [9:0] sub_ln61_5_fu_1120_p2;
wire   [10:0] zext_ln1026_fu_1142_p1;
wire   [10:0] zext_ln1026_1_fu_1146_p1;
wire   [10:0] sub_ln1026_fu_1150_p2;
wire   [9:0] trunc_ln61_6_fu_1156_p1;
wire   [0:0] tmp_14_fu_1166_p3;
wire   [9:0] sub_ln61_6_fu_1160_p2;
wire   [10:0] zext_ln1027_fu_1182_p1;
wire   [10:0] zext_ln1027_1_fu_1186_p1;
wire   [10:0] sub_ln1027_fu_1190_p2;
wire   [9:0] trunc_ln61_7_fu_1196_p1;
wire   [0:0] tmp_15_fu_1206_p3;
wire   [9:0] sub_ln61_7_fu_1200_p2;
wire   [10:0] zext_ln1028_fu_1222_p1;
wire   [10:0] zext_ln1028_1_fu_1226_p1;
wire   [10:0] sub_ln1028_fu_1230_p2;
wire   [9:0] trunc_ln61_8_fu_1236_p1;
wire   [0:0] tmp_16_fu_1246_p3;
wire   [9:0] sub_ln61_8_fu_1240_p2;
wire   [9:0] DRh_fu_1054_p3;
wire   [9:0] DGh_fu_1134_p3;
wire   [10:0] zext_ln1030_fu_1262_p1;
wire   [10:0] zext_ln1030_1_fu_1266_p1;
wire   [10:0] add_ln1030_fu_1270_p2;
wire   [9:0] DBh_fu_1214_p3;
wire   [11:0] zext_ln1030_2_fu_1276_p1;
wire   [11:0] zext_ln1030_3_fu_1280_p1;
wire   [9:0] DRv_fu_1094_p3;
wire   [9:0] DGv_fu_1174_p3;
wire   [10:0] zext_ln1030_4_fu_1290_p1;
wire   [10:0] zext_ln1030_5_fu_1294_p1;
wire   [10:0] add_ln1030_2_fu_1298_p2;
wire   [9:0] DBv_fu_1254_p3;
wire   [11:0] zext_ln1030_6_fu_1304_p1;
wire   [11:0] zext_ln1030_7_fu_1308_p1;
wire   [11:0] add_ln1030_1_fu_1284_p2;
wire   [11:0] add_ln1030_3_fu_1312_p2;
wire   [10:0] sub_ln1033_fu_1324_p2;
wire   [10:0] sub_ln1033_1_fu_1330_p2;
wire  signed [11:0] sext_ln1033_fu_1336_p1;
wire  signed [11:0] sext_ln1033_1_fu_1340_p1;
wire  signed [12:0] sext_ln1033_2_fu_1350_p1;
wire   [12:0] sub_ln1033_2_fu_1354_p2;
wire   [10:0] lshr_ln1033_1_cast_fu_1360_p4;
wire   [10:0] sub_ln1034_fu_1376_p2;
wire   [10:0] sub_ln1034_1_fu_1382_p2;
wire  signed [11:0] sext_ln1034_fu_1388_p1;
wire  signed [11:0] sext_ln1034_1_fu_1392_p1;
wire  signed [12:0] sext_ln1034_2_fu_1402_p1;
wire   [12:0] sub_ln1034_2_fu_1406_p2;
wire   [10:0] lshr_ln1034_1_cast_fu_1412_p4;
wire   [10:0] sub_ln1039_fu_1428_p2;
wire   [10:0] sub_ln1039_1_fu_1434_p2;
wire  signed [11:0] sext_ln1039_fu_1440_p1;
wire  signed [11:0] sext_ln1039_1_fu_1444_p1;
wire  signed [11:0] add_ln1039_fu_1448_p2;
wire  signed [12:0] sext_ln1039_2_fu_1454_p1;
wire   [12:0] sub_ln1039_2_fu_1466_p2;
wire   [10:0] lshr_ln1039_1_cast_fu_1472_p4;
wire   [0:0] tmp_19_fu_1458_p3;
wire   [10:0] sub_ln1039_3_fu_1482_p2;
wire   [10:0] zext_ln2_fu_1488_p4;
wire   [10:0] sub_ln1040_fu_1506_p2;
wire   [10:0] sub_ln1040_1_fu_1512_p2;
wire  signed [11:0] sext_ln1040_fu_1518_p1;
wire  signed [11:0] sext_ln1040_1_fu_1522_p1;
wire  signed [11:0] add_ln1040_fu_1526_p2;
wire  signed [12:0] sext_ln1040_2_fu_1532_p1;
wire   [12:0] sub_ln1040_2_fu_1544_p2;
wire   [10:0] lshr_ln1040_1_cast_fu_1550_p4;
wire   [0:0] tmp_20_fu_1536_p3;
wire   [10:0] sub_ln1040_3_fu_1560_p2;
wire   [10:0] zext_ln3_fu_1566_p4;
wire   [0:0] tmp_17_fu_1584_p3;
wire   [10:0] zext_ln_fu_1591_p4;
wire   [0:0] tmp_18_fu_1611_p3;
wire   [10:0] zext_ln1_fu_1618_p4;
wire   [10:0] select_ln1033_fu_1600_p3;
wire   [10:0] r_0_in_i_v_v_fu_1634_p3;
wire   [11:0] zext_ln1034_1_fu_1607_p1;
wire  signed [11:0] r_0_in_i_v_v_cast_fu_1640_p1;
wire  signed [11:0] r_0_in_i_fu_1644_p2;
wire   [10:0] select_ln1034_fu_1627_p3;
wire   [10:0] b_0_in_i_v_v_fu_1654_p3;
wire  signed [11:0] b_0_in_i_v_v_cast_fu_1660_p1;
wire  signed [11:0] b_0_in_i_fu_1664_p2;
wire  signed [13:0] r_0_in_i_cast1_fu_1650_p1;
wire   [1:0] tmp_22_fu_1690_p4;
wire   [0:0] tmp_21_fu_1682_p3;
wire   [0:0] xor_ln1046_fu_1706_p2;
wire   [0:0] icmp_ln1042_fu_1700_p2;
wire   [0:0] or_ln1042_fu_1720_p2;
wire   [9:0] select_ln1042_fu_1712_p3;
wire   [9:0] trunc_ln1046_fu_1678_p1;
wire  signed [13:0] sext_ln1048_fu_1670_p1;
wire   [1:0] tmp_24_fu_1742_p4;
wire   [0:0] tmp_23_fu_1734_p3;
wire   [0:0] xor_ln1048_fu_1758_p2;
wire   [0:0] icmp_ln1043_fu_1752_p2;
wire   [0:0] or_ln1043_fu_1772_p2;
wire   [9:0] select_ln1043_fu_1764_p3;
wire   [9:0] trunc_ln1048_fu_1674_p1;
wire   [9:0] select_ln1046_fu_1726_p3;
wire   [9:0] select_ln1048_fu_1778_p3;
wire   [9:0] phi_ln1046_fu_1786_p3;
wire   [9:0] phi_ln1048_fu_1793_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_block_pp0;
reg    ap_predicate_op66_load_state1;
reg    ap_enable_operation_66;
reg    ap_enable_state1_pp0_iter0_stage0;
reg    ap_predicate_op94_load_state2;
reg    ap_enable_operation_94;
reg    ap_enable_state2_pp0_iter1_stage0;
reg    ap_predicate_op107_store_state2;
reg    ap_enable_operation_107;
reg    ap_predicate_op68_load_state1;
reg    ap_enable_operation_68;
reg    ap_predicate_op98_load_state2;
reg    ap_enable_operation_98;
reg    ap_predicate_op133_store_state2;
reg    ap_enable_operation_133;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_228;
reg    ap_condition_1254;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 x_fu_160 = 11'd0;
#0 p_0_0_0116317361747_i_fu_164 = 10'd0;
#0 p_0_0_0116217381749_i_fu_168 = 10'd0;
#0 p_0_0_0116117401751_i_fu_172 = 10'd0;
#0 right_fu_176 = 10'd0;
#0 right_1_fu_180 = 10'd0;
#0 right_2_fu_184 = 10'd0;
#0 p_0_0_01176_217301759_i_fu_188 = 10'd0;
#0 p_0_0_01175_217321761_i_fu_192 = 10'd0;
#0 p_0_0_01174_217341763_i_fu_196 = 10'd0;
#0 p_0_0_0_0_011551660_i_fu_200 = 10'd0;
#0 p_0_1_0_0_011561663_i_fu_204 = 10'd0;
#0 p_0_2_0_0_011571666_i_fu_208 = 10'd0;
#0 ap_done_reg = 1'b0;
end

design_1_v_demosaic_0_2_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_lineBuffer_1_RAM_AUTO_1R1W #(
    .DataWidth( 30 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
lineBuffer_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lineBuffer_2_address0),
    .ce0(lineBuffer_2_ce0_local),
    .we0(lineBuffer_2_we0_local),
    .d0(LineBufVal_4_fu_942_p4),
    .address1(lineBuffer_2_address1),
    .ce1(lineBuffer_2_ce1_local),
    .q1(lineBuffer_2_q1)
);

design_1_v_demosaic_0_2_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_lineBuffer_1_RAM_AUTO_1R1W #(
    .DataWidth( 30 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
lineBuffer_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lineBuffer_address0),
    .ce0(lineBuffer_ce0_local),
    .we0(lineBuffer_we0_local),
    .d0(imgRB_dout),
    .address1(lineBuffer_address1),
    .ce1(lineBuffer_ce1_local),
    .q1(lineBuffer_q1)
);

design_1_v_demosaic_0_2_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_228)) begin
        if (((icmp_ln891_reg_1978 == 1'd0) & (icmp_ln881_reg_1974 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_down_1_reg_442 <= p_0_0_01175_217321761_i_fu_192;
        end else if (((icmp_ln891_reg_1978 == 1'd1) & (icmp_ln881_reg_1974 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_down_1_reg_442 <= select_ln957_10_fu_849_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_down_1_reg_442 <= ap_phi_reg_pp0_iter1_down_1_reg_442;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_228)) begin
        if (((icmp_ln891_reg_1978 == 1'd0) & (icmp_ln881_reg_1974 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_down_2_reg_433 <= p_0_0_01174_217341763_i_fu_196;
        end else if (((icmp_ln891_reg_1978 == 1'd1) & (icmp_ln881_reg_1974 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_down_2_reg_433 <= select_ln957_9_fu_842_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_down_2_reg_433 <= ap_phi_reg_pp0_iter1_down_2_reg_433;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_228)) begin
        if (((icmp_ln891_reg_1978 == 1'd0) & (icmp_ln881_reg_1974 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_down_reg_451 <= p_0_0_01176_217301759_i_fu_188;
        end else if (((icmp_ln891_reg_1978 == 1'd1) & (icmp_ln881_reg_1974 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_down_reg_451 <= select_ln957_11_fu_856_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_down_reg_451 <= ap_phi_reg_pp0_iter1_down_reg_451;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_228)) begin
        if (((icmp_ln891_reg_1978 == 1'd0) & (icmp_ln881_reg_1974 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_left_1_reg_469 <= p_0_1_0_0_011561663_i_fu_204;
        end else if (((icmp_ln891_reg_1978 == 1'd1) & (icmp_ln881_reg_1974 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_left_1_reg_469 <= select_ln957_4_fu_807_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_left_1_reg_469 <= ap_phi_reg_pp0_iter1_left_1_reg_469;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_228)) begin
        if (((icmp_ln891_reg_1978 == 1'd0) & (icmp_ln881_reg_1974 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_left_2_reg_460 <= p_0_2_0_0_011571666_i_fu_208;
        end else if (((icmp_ln891_reg_1978 == 1'd1) & (icmp_ln881_reg_1974 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_left_2_reg_460 <= select_ln957_5_fu_814_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_left_2_reg_460 <= ap_phi_reg_pp0_iter1_left_2_reg_460;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_228)) begin
        if (((icmp_ln891_reg_1978 == 1'd0) & (icmp_ln881_reg_1974 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_left_reg_478 <= p_0_0_0_0_011551660_i_fu_200;
        end else if (((icmp_ln891_reg_1978 == 1'd1) & (icmp_ln881_reg_1974 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_left_reg_478 <= select_ln957_3_fu_800_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_left_reg_478 <= ap_phi_reg_pp0_iter1_left_reg_478;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_228)) begin
        if (((icmp_ln891_reg_1978 == 1'd0) & (icmp_ln881_reg_1974 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_up_1_reg_496 <= p_0_0_0116217381749_i_fu_168;
        end else if (((icmp_ln891_reg_1978 == 1'd1) & (icmp_ln881_reg_1974 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_up_1_reg_496 <= select_ln957_7_fu_828_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_up_1_reg_496 <= ap_phi_reg_pp0_iter1_up_1_reg_496;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_228)) begin
        if (((icmp_ln891_reg_1978 == 1'd0) & (icmp_ln881_reg_1974 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_up_2_reg_487 <= p_0_0_0116117401751_i_fu_172;
        end else if (((icmp_ln891_reg_1978 == 1'd1) & (icmp_ln881_reg_1974 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_up_2_reg_487 <= select_ln957_6_fu_821_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_up_2_reg_487 <= ap_phi_reg_pp0_iter1_up_2_reg_487;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_228)) begin
        if (((icmp_ln891_reg_1978 == 1'd0) & (icmp_ln881_reg_1974 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_up_reg_505 <= p_0_0_0116317361747_i_fu_164;
        end else if (((icmp_ln891_reg_1978 == 1'd1) & (icmp_ln881_reg_1974 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_up_reg_505 <= select_ln957_8_fu_835_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_up_reg_505 <= ap_phi_reg_pp0_iter1_up_reg_505;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_0116117401751_i_fu_172 <= p_0_0_0116117401752_lcssa1788_i;
        end else if ((1'b1 == ap_condition_1254)) begin
            p_0_0_0116117401751_i_fu_172 <= {{lineBuffer_2_q1[29:20]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_0116217381749_i_fu_168 <= p_0_0_0116217381750_lcssa1786_i;
        end else if ((1'b1 == ap_condition_1254)) begin
            p_0_0_0116217381749_i_fu_168 <= {{lineBuffer_2_q1[19:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_0116317361747_i_fu_164 <= p_0_0_0116317361748_lcssa1784_i;
        end else if ((1'b1 == ap_condition_1254)) begin
            p_0_0_0116317361747_i_fu_164 <= trunc_ln902_1_fu_729_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_01174_217341763_i_fu_196 <= p_0_0_01174_217341764_lcssa1800_i;
        end else if ((1'b1 == ap_condition_1254)) begin
            p_0_0_01174_217341763_i_fu_196 <= ap_phi_mux_p_0_0_01174_21734_ph_i_phi_fu_379_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_01175_217321761_i_fu_192 <= p_0_0_01175_217321762_lcssa1798_i;
        end else if ((1'b1 == ap_condition_1254)) begin
            p_0_0_01175_217321761_i_fu_192 <= ap_phi_mux_p_0_0_01175_21732_ph_i_phi_fu_388_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_01176_217301759_i_fu_188 <= p_0_0_01176_217301760_lcssa1796_i;
        end else if ((1'b1 == ap_condition_1254)) begin
            p_0_0_01176_217301759_i_fu_188 <= ap_phi_mux_p_0_0_01176_21730_ph_i_phi_fu_397_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_0_0_011551660_i_fu_200 <= p_0_0_0_0_011551658_lcssa1702_i;
        end else if (((icmp_ln881_reg_1974 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            p_0_0_0_0_011551660_i_fu_200 <= ap_phi_mux_pix_phi_fu_426_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_1_0_0_011561663_i_fu_204 <= p_0_1_0_0_011561661_lcssa1704_i;
        end else if (((icmp_ln881_reg_1974 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            p_0_1_0_0_011561663_i_fu_204 <= ap_phi_mux_pix_7_phi_fu_416_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_2_0_0_011571666_i_fu_208 <= p_0_2_0_0_011571664_lcssa1706_i;
        end else if (((icmp_ln881_reg_1974 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            p_0_2_0_0_011571666_i_fu_208 <= ap_phi_mux_pix_8_phi_fu_406_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_228)) begin
        if (((icmp_ln891_reg_1978 == 1'd0) & (icmp_ln881_reg_1974 == 1'd0))) begin
            pix_7_reg_413 <= right_1_fu_180;
        end else if (((icmp_ln891_reg_1978 == 1'd1) & (icmp_ln881_reg_1974 == 1'd0))) begin
            pix_7_reg_413 <= select_ln957_1_fu_784_p3;
        end else if (~(icmp_ln881_reg_1974 == 1'd1)) begin
            pix_7_reg_413 <= ap_phi_reg_pp0_iter1_pix_7_reg_413;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_228)) begin
        if (((icmp_ln891_reg_1978 == 1'd0) & (icmp_ln881_reg_1974 == 1'd0))) begin
            pix_8_reg_403 <= right_2_fu_184;
        end else if (((icmp_ln891_reg_1978 == 1'd1) & (icmp_ln881_reg_1974 == 1'd0))) begin
            pix_8_reg_403 <= select_ln957_2_fu_792_p3;
        end else if (~(icmp_ln881_reg_1974 == 1'd1)) begin
            pix_8_reg_403 <= ap_phi_reg_pp0_iter1_pix_8_reg_403;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_228)) begin
        if (((icmp_ln891_reg_1978 == 1'd0) & (icmp_ln881_reg_1974 == 1'd0))) begin
            pix_reg_423 <= right_fu_176;
        end else if (((icmp_ln891_reg_1978 == 1'd1) & (icmp_ln881_reg_1974 == 1'd0))) begin
            pix_reg_423 <= select_ln957_fu_776_p3;
        end else if (~(icmp_ln881_reg_1974 == 1'd1)) begin
            pix_reg_423 <= ap_phi_reg_pp0_iter1_pix_reg_423;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            right_1_fu_180 <= p_0_1_0_0_011501755_lcssa1792_i;
        end else if ((1'b1 == ap_condition_1254)) begin
            right_1_fu_180 <= {{lineBuffer_q1[19:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            right_2_fu_184 <= p_0_2_0_0_011511757_lcssa1794_i;
        end else if ((1'b1 == ap_condition_1254)) begin
            right_2_fu_184 <= {{lineBuffer_q1[29:20]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            right_fu_176 <= p_0_0_0_0_011491753_lcssa1790_i;
        end else if ((1'b1 == ap_condition_1254)) begin
            right_fu_176 <= trunc_ln902_fu_706_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln881_fu_594_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
            x_fu_160 <= x_8_fu_600_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_160 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln1033_reg_2140 <= add_ln1033_fu_1344_p2;
        add_ln1034_reg_2151 <= add_ln1034_fu_1396_p2;
        and_ln1052_reg_2016_pp0_iter2_reg <= and_ln1052_reg_2016_pp0_iter1_reg;
        icmp_ln1014_reg_2010_pp0_iter2_reg <= icmp_ln1014_reg_2010_pp0_iter1_reg;
        icmp_ln1030_reg_2134 <= icmp_ln1030_fu_1318_p2;
        pix_7_reg_413_pp0_iter2_reg <= pix_7_reg_413;
        pix_8_reg_403_pp0_iter2_reg <= pix_8_reg_403;
        pix_reg_423_pp0_iter2_reg <= pix_reg_423;
        select_ln1039_reg_2162 <= select_ln1039_fu_1498_p3;
        select_ln1040_reg_2167 <= select_ln1040_fu_1576_p3;
        sub_ln1033_3_reg_2146 <= sub_ln1033_3_fu_1370_p2;
        sub_ln1034_3_reg_2157 <= sub_ln1034_3_fu_1422_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln1052_reg_2016 <= and_ln1052_fu_656_p2;
        and_ln1052_reg_2016_pp0_iter1_reg <= and_ln1052_reg_2016;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        cmp161_i_reg_1994 <= cmp161_i_fu_622_p2;
        cmp203_i_reg_1969 <= cmp203_i_fu_520_p2;
        cmp59_i_reg_1965 <= cmp59_i_fu_514_p2;
        icmp_ln1014_reg_2010 <= icmp_ln1014_fu_644_p2;
        icmp_ln1014_reg_2010_pp0_iter1_reg <= icmp_ln1014_reg_2010;
        icmp_ln881_reg_1974 <= icmp_ln881_fu_594_p2;
        icmp_ln881_reg_1974_pp0_iter1_reg <= icmp_ln881_reg_1974;
        icmp_ln891_reg_1978 <= icmp_ln891_fu_616_p2;
        lineBuffer_2_addr_reg_1988 <= zext_ln881_fu_610_p1;
        lineBuffer_addr_reg_1982 <= zext_ln881_fu_610_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_down_1_reg_442 <= ap_phi_reg_pp0_iter0_down_1_reg_442;
        ap_phi_reg_pp0_iter1_down_2_reg_433 <= ap_phi_reg_pp0_iter0_down_2_reg_433;
        ap_phi_reg_pp0_iter1_down_reg_451 <= ap_phi_reg_pp0_iter0_down_reg_451;
        ap_phi_reg_pp0_iter1_left_1_reg_469 <= ap_phi_reg_pp0_iter0_left_1_reg_469;
        ap_phi_reg_pp0_iter1_left_2_reg_460 <= ap_phi_reg_pp0_iter0_left_2_reg_460;
        ap_phi_reg_pp0_iter1_left_reg_478 <= ap_phi_reg_pp0_iter0_left_reg_478;
        ap_phi_reg_pp0_iter1_up_1_reg_496 <= ap_phi_reg_pp0_iter0_up_1_reg_496;
        ap_phi_reg_pp0_iter1_up_2_reg_487 <= ap_phi_reg_pp0_iter0_up_2_reg_487;
        ap_phi_reg_pp0_iter1_up_reg_505 <= ap_phi_reg_pp0_iter0_up_reg_505;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_0_0116117401751_i_load_reg_2032 <= p_0_0_0116117401751_i_fu_172;
        p_0_0_0116217381749_i_load_reg_2026 <= p_0_0_0116217381749_i_fu_168;
        p_0_0_0116317361747_i_load_reg_2020 <= p_0_0_0116317361747_i_fu_164;
        p_0_0_01174_217341763_i_load_reg_2065 <= p_0_0_01174_217341763_i_fu_196;
        p_0_0_01175_217321761_i_load_reg_2059 <= p_0_0_01175_217321761_i_fu_192;
        p_0_0_01176_217301759_i_load_reg_2053 <= p_0_0_01176_217301759_i_fu_188;
        p_0_0_0_0_011551660_i_load_reg_2071 <= p_0_0_0_0_011551660_i_fu_200;
        p_0_1_0_0_011561663_i_load_reg_2077 <= p_0_1_0_0_011561663_i_fu_204;
        p_0_2_0_0_011571666_i_load_reg_2083 <= p_0_2_0_0_011571666_i_fu_208;
        right_3_reg_2038 <= right_fu_176;
        right_4_reg_2043 <= right_1_fu_180;
        right_5_reg_2048 <= right_2_fu_184;
    end
end

always @ (*) begin
    if (((icmp_ln881_fu_594_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln881_reg_1974 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln891_reg_1978 == 1'd1) & (icmp_ln881_reg_1974 == 1'd0))) begin
        if ((cmp59_i_reg_1965 == 1'd0)) begin
            ap_phi_mux_p_0_0_01174_21734_ph_i_phi_fu_379_p4 = {{lineBuffer_q1[29:20]}};
        end else if ((cmp59_i_reg_1965 == 1'd1)) begin
            ap_phi_mux_p_0_0_01174_21734_ph_i_phi_fu_379_p4 = {{imgRB_dout[29:20]}};
        end else begin
            ap_phi_mux_p_0_0_01174_21734_ph_i_phi_fu_379_p4 = ap_phi_reg_pp0_iter1_p_0_0_01174_21734_ph_i_reg_376;
        end
    end else begin
        ap_phi_mux_p_0_0_01174_21734_ph_i_phi_fu_379_p4 = ap_phi_reg_pp0_iter1_p_0_0_01174_21734_ph_i_reg_376;
    end
end

always @ (*) begin
    if (((icmp_ln891_reg_1978 == 1'd1) & (icmp_ln881_reg_1974 == 1'd0))) begin
        if ((cmp59_i_reg_1965 == 1'd0)) begin
            ap_phi_mux_p_0_0_01175_21732_ph_i_phi_fu_388_p4 = {{lineBuffer_q1[19:10]}};
        end else if ((cmp59_i_reg_1965 == 1'd1)) begin
            ap_phi_mux_p_0_0_01175_21732_ph_i_phi_fu_388_p4 = {{imgRB_dout[19:10]}};
        end else begin
            ap_phi_mux_p_0_0_01175_21732_ph_i_phi_fu_388_p4 = ap_phi_reg_pp0_iter1_p_0_0_01175_21732_ph_i_reg_385;
        end
    end else begin
        ap_phi_mux_p_0_0_01175_21732_ph_i_phi_fu_388_p4 = ap_phi_reg_pp0_iter1_p_0_0_01175_21732_ph_i_reg_385;
    end
end

always @ (*) begin
    if (((icmp_ln891_reg_1978 == 1'd1) & (icmp_ln881_reg_1974 == 1'd0))) begin
        if ((cmp59_i_reg_1965 == 1'd0)) begin
            ap_phi_mux_p_0_0_01176_21730_ph_i_phi_fu_397_p4 = trunc_ln902_fu_706_p1;
        end else if ((cmp59_i_reg_1965 == 1'd1)) begin
            ap_phi_mux_p_0_0_01176_21730_ph_i_phi_fu_397_p4 = trunc_ln913_fu_749_p1;
        end else begin
            ap_phi_mux_p_0_0_01176_21730_ph_i_phi_fu_397_p4 = ap_phi_reg_pp0_iter1_p_0_0_01176_21730_ph_i_reg_394;
        end
    end else begin
        ap_phi_mux_p_0_0_01176_21730_ph_i_phi_fu_397_p4 = ap_phi_reg_pp0_iter1_p_0_0_01176_21730_ph_i_reg_394;
    end
end

always @ (*) begin
    if ((icmp_ln881_reg_1974 == 1'd0)) begin
        if ((icmp_ln891_reg_1978 == 1'd0)) begin
            ap_phi_mux_pix_7_phi_fu_416_p4 = right_1_fu_180;
        end else if ((icmp_ln891_reg_1978 == 1'd1)) begin
            ap_phi_mux_pix_7_phi_fu_416_p4 = select_ln957_1_fu_784_p3;
        end else begin
            ap_phi_mux_pix_7_phi_fu_416_p4 = ap_phi_reg_pp0_iter1_pix_7_reg_413;
        end
    end else begin
        ap_phi_mux_pix_7_phi_fu_416_p4 = ap_phi_reg_pp0_iter1_pix_7_reg_413;
    end
end

always @ (*) begin
    if ((icmp_ln881_reg_1974 == 1'd0)) begin
        if ((icmp_ln891_reg_1978 == 1'd0)) begin
            ap_phi_mux_pix_8_phi_fu_406_p4 = right_2_fu_184;
        end else if ((icmp_ln891_reg_1978 == 1'd1)) begin
            ap_phi_mux_pix_8_phi_fu_406_p4 = select_ln957_2_fu_792_p3;
        end else begin
            ap_phi_mux_pix_8_phi_fu_406_p4 = ap_phi_reg_pp0_iter1_pix_8_reg_403;
        end
    end else begin
        ap_phi_mux_pix_8_phi_fu_406_p4 = ap_phi_reg_pp0_iter1_pix_8_reg_403;
    end
end

always @ (*) begin
    if ((icmp_ln881_reg_1974 == 1'd0)) begin
        if ((icmp_ln891_reg_1978 == 1'd0)) begin
            ap_phi_mux_pix_phi_fu_426_p4 = right_fu_176;
        end else if ((icmp_ln891_reg_1978 == 1'd1)) begin
            ap_phi_mux_pix_phi_fu_426_p4 = select_ln957_fu_776_p3;
        end else begin
            ap_phi_mux_pix_phi_fu_426_p4 = ap_phi_reg_pp0_iter1_pix_reg_423;
        end
    end else begin
        ap_phi_mux_pix_phi_fu_426_p4 = ap_phi_reg_pp0_iter1_pix_reg_423;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_z = 11'd0;
    end else begin
        ap_sig_allocacmp_z = x_fu_160;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op103_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        imgRB_blk_n = imgRB_empty_n;
    end else begin
        imgRB_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op103_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        imgRB_read = 1'b1;
    end else begin
        imgRB_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'd1 == and_ln1052_reg_2016_pp0_iter2_reg) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        imgRgb_blk_n = imgRgb_full_n;
    end else begin
        imgRgb_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln1052_reg_2016_pp0_iter2_reg) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        imgRgb_write = 1'b1;
    end else begin
        imgRgb_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lineBuffer_2_ce0_local = 1'b1;
    end else begin
        lineBuffer_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lineBuffer_2_ce1_local = 1'b1;
    end else begin
        lineBuffer_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln891_reg_1978 == 1'd1) & (icmp_ln881_reg_1974 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lineBuffer_2_we0_local = 1'b1;
    end else begin
        lineBuffer_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lineBuffer_ce0_local = 1'b1;
    end else begin
        lineBuffer_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lineBuffer_ce1_local = 1'b1;
    end else begin
        lineBuffer_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (cmp59_i_reg_1965 == 1'd1) & (icmp_ln891_reg_1978 == 1'd1) & (icmp_ln881_reg_1974 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lineBuffer_we0_local = 1'b1;
    end else begin
        lineBuffer_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1974_pp0_iter1_reg == 1'd1))) begin
        p_0_0_0116117401751_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0116117401751_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1974_pp0_iter1_reg == 1'd1))) begin
        p_0_0_0116217381749_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0116217381749_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1974_pp0_iter1_reg == 1'd1))) begin
        p_0_0_0116317361747_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0116317361747_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1974_pp0_iter1_reg == 1'd1))) begin
        p_0_0_01174_217341763_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_01174_217341763_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1974_pp0_iter1_reg == 1'd1))) begin
        p_0_0_01175_217321761_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_01175_217321761_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1974_pp0_iter1_reg == 1'd1))) begin
        p_0_0_01176_217301759_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_01176_217301759_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1974_pp0_iter1_reg == 1'd1))) begin
        p_0_0_0_0_011551660_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0_0_011551660_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1974_pp0_iter1_reg == 1'd1))) begin
        p_0_1_0_0_011561663_i_out_ap_vld = 1'b1;
    end else begin
        p_0_1_0_0_011561663_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1974_pp0_iter1_reg == 1'd1))) begin
        p_0_2_0_0_011571666_i_out_ap_vld = 1'b1;
    end else begin
        p_0_2_0_0_011571666_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1974_pp0_iter1_reg == 1'd1))) begin
        right_1_out_ap_vld = 1'b1;
    end else begin
        right_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1974_pp0_iter1_reg == 1'd1))) begin
        right_2_out_ap_vld = 1'b1;
    end else begin
        right_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1974_pp0_iter1_reg == 1'd1))) begin
        right_out_ap_vld = 1'b1;
    end else begin
        right_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign DBh_fu_1214_p3 = ((tmp_15_fu_1206_p3[0:0] == 1'b1) ? sub_ln61_7_fu_1200_p2 : trunc_ln61_7_fu_1196_p1);

assign DBv_fu_1254_p3 = ((tmp_16_fu_1246_p3[0:0] == 1'b1) ? sub_ln61_8_fu_1240_p2 : trunc_ln61_8_fu_1236_p1);

assign DGh_fu_1134_p3 = ((tmp_13_fu_1126_p3[0:0] == 1'b1) ? sub_ln61_5_fu_1120_p2 : trunc_ln61_5_fu_1116_p1);

assign DGv_fu_1174_p3 = ((tmp_14_fu_1166_p3[0:0] == 1'b1) ? sub_ln61_6_fu_1160_p2 : trunc_ln61_6_fu_1156_p1);

assign DRh_fu_1054_p3 = ((tmp_11_fu_1046_p3[0:0] == 1'b1) ? sub_ln61_fu_1040_p2 : trunc_ln61_fu_1036_p1);

assign DRv_fu_1094_p3 = ((tmp_12_fu_1086_p3[0:0] == 1'b1) ? sub_ln61_4_fu_1080_p2 : trunc_ln61_4_fu_1076_p1);

assign LineBufVal_4_fu_942_p4 = {{{tmp_6_i_fu_932_p4}, {tmp_5_i_fu_922_p4}}, {empty_154_fu_918_p1}};

assign add_ln1030_1_fu_1284_p2 = (zext_ln1030_2_fu_1276_p1 + zext_ln1030_3_fu_1280_p1);

assign add_ln1030_2_fu_1298_p2 = (zext_ln1030_4_fu_1290_p1 + zext_ln1030_5_fu_1294_p1);

assign add_ln1030_3_fu_1312_p2 = (zext_ln1030_6_fu_1304_p1 + zext_ln1030_7_fu_1308_p1);

assign add_ln1030_fu_1270_p2 = (zext_ln1030_fu_1262_p1 + zext_ln1030_1_fu_1266_p1);

assign add_ln1033_fu_1344_p2 = ($signed(sext_ln1033_fu_1336_p1) + $signed(sext_ln1033_1_fu_1340_p1));

assign add_ln1034_fu_1396_p2 = ($signed(sext_ln1034_fu_1388_p1) + $signed(sext_ln1034_1_fu_1392_p1));

assign add_ln1039_fu_1448_p2 = ($signed(sext_ln1039_fu_1440_p1) + $signed(sext_ln1039_1_fu_1444_p1));

assign add_ln1040_fu_1526_p2 = ($signed(sext_ln1040_fu_1518_p1) + $signed(sext_ln1040_1_fu_1522_p1));

assign and_ln1052_fu_656_p2 = (icmp_ln1052_fu_650_p2 & cmp203_i_fu_520_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((ap_predicate_op103_read_state2 == 1'b1) & (imgRB_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = ((imgRgb_full_n == 1'b0) & (1'd1 == and_ln1052_reg_2016_pp0_iter2_reg));
end

always @ (*) begin
    ap_condition_1254 = ((icmp_ln891_reg_1978 == 1'd1) & (icmp_ln881_reg_1974 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_228 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

always @ (*) begin
    ap_enable_operation_107 = (ap_predicate_op107_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_133 = (ap_predicate_op133_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_66 = (ap_predicate_op66_load_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_68 = (ap_predicate_op68_load_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_94 = (ap_predicate_op94_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_98 = (ap_predicate_op98_load_state2 == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

always @ (*) begin
    ap_enable_state1_pp0_iter0_stage0 = ((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state2_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_down_1_reg_442 = 'bx;

assign ap_phi_reg_pp0_iter0_down_2_reg_433 = 'bx;

assign ap_phi_reg_pp0_iter0_down_reg_451 = 'bx;

assign ap_phi_reg_pp0_iter0_left_1_reg_469 = 'bx;

assign ap_phi_reg_pp0_iter0_left_2_reg_460 = 'bx;

assign ap_phi_reg_pp0_iter0_left_reg_478 = 'bx;

assign ap_phi_reg_pp0_iter0_up_1_reg_496 = 'bx;

assign ap_phi_reg_pp0_iter0_up_2_reg_487 = 'bx;

assign ap_phi_reg_pp0_iter0_up_reg_505 = 'bx;

assign ap_phi_reg_pp0_iter1_p_0_0_01174_21734_ph_i_reg_376 = 'bx;

assign ap_phi_reg_pp0_iter1_p_0_0_01175_21732_ph_i_reg_385 = 'bx;

assign ap_phi_reg_pp0_iter1_p_0_0_01176_21730_ph_i_reg_394 = 'bx;

assign ap_phi_reg_pp0_iter1_pix_7_reg_413 = 'bx;

assign ap_phi_reg_pp0_iter1_pix_8_reg_403 = 'bx;

assign ap_phi_reg_pp0_iter1_pix_reg_423 = 'bx;

always @ (*) begin
    ap_predicate_op103_read_state2 = ((cmp59_i_reg_1965 == 1'd1) & (icmp_ln891_reg_1978 == 1'd1) & (icmp_ln881_reg_1974 == 1'd0));
end

always @ (*) begin
    ap_predicate_op107_store_state2 = ((cmp59_i_reg_1965 == 1'd1) & (icmp_ln891_reg_1978 == 1'd1) & (icmp_ln881_reg_1974 == 1'd0));
end

always @ (*) begin
    ap_predicate_op133_store_state2 = ((icmp_ln891_reg_1978 == 1'd1) & (icmp_ln881_reg_1974 == 1'd0));
end

always @ (*) begin
    ap_predicate_op66_load_state1 = ((icmp_ln881_fu_594_p2 == 1'd0) & (icmp_ln891_fu_616_p2 == 1'd1));
end

always @ (*) begin
    ap_predicate_op68_load_state1 = ((icmp_ln881_fu_594_p2 == 1'd0) & (icmp_ln891_fu_616_p2 == 1'd1));
end

always @ (*) begin
    ap_predicate_op94_load_state2 = ((icmp_ln891_reg_1978 == 1'd1) & (icmp_ln881_reg_1974 == 1'd0));
end

always @ (*) begin
    ap_predicate_op98_load_state2 = ((icmp_ln891_reg_1978 == 1'd1) & (icmp_ln881_reg_1974 == 1'd0));
end

assign ap_ready = ap_ready_sig;

assign b_0_in_i_fu_1664_p2 = ($signed(zext_ln1034_1_fu_1607_p1) - $signed(b_0_in_i_v_v_cast_fu_1660_p1));

assign b_0_in_i_v_v_cast_fu_1660_p1 = $signed(b_0_in_i_v_v_fu_1654_p3);

assign b_0_in_i_v_v_fu_1654_p3 = ((icmp_ln1030_reg_2134[0:0] == 1'b1) ? select_ln1034_fu_1627_p3 : select_ln1040_reg_2167);

assign cmp161_i_fu_622_p2 = ((ap_sig_allocacmp_z == 11'd0) ? 1'b1 : 1'b0);

assign cmp203_i_fu_520_p2 = ((y != 11'd0) ? 1'b1 : 1'b0);

assign cmp59_i_fu_514_p2 = ((y < height_val4_load) ? 1'b1 : 1'b0);

assign empty_154_fu_918_p1 = storemerge_1_in_i_fu_911_p3[9:0];

assign icmp_ln1014_fu_644_p2 = ((xor_i == zext_ln1014_fu_640_p1) ? 1'b1 : 1'b0);

assign icmp_ln1030_fu_1318_p2 = ((add_ln1030_1_fu_1284_p2 < add_ln1030_3_fu_1312_p2) ? 1'b1 : 1'b0);

assign icmp_ln1042_fu_1700_p2 = ((tmp_22_fu_1690_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln1043_fu_1752_p2 = ((tmp_24_fu_1742_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln1052_fu_650_p2 = ((ap_sig_allocacmp_z != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln881_fu_594_p2 = ((ap_sig_allocacmp_z == loopWidth) ? 1'b1 : 1'b0);

assign icmp_ln891_fu_616_p2 = ((ap_sig_allocacmp_z < width_val8_load) ? 1'b1 : 1'b0);

assign imgRgb_din = {{{phi_ln1046_fu_1786_p3}, {phi_ln1048_fu_1793_p3}}, {pix_7_reg_413_pp0_iter2_reg}};

assign lineBuffer_2_address0 = lineBuffer_2_addr_reg_1988;

assign lineBuffer_2_address1 = zext_ln881_fu_610_p1;

assign lineBuffer_address0 = lineBuffer_addr_reg_1982;

assign lineBuffer_address1 = zext_ln881_fu_610_p1;

assign lshr_ln1033_1_cast_fu_1360_p4 = {{sub_ln1033_2_fu_1354_p2[11:1]}};

assign lshr_ln1034_1_cast_fu_1412_p4 = {{sub_ln1034_2_fu_1406_p2[11:1]}};

assign lshr_ln1039_1_cast_fu_1472_p4 = {{sub_ln1039_2_fu_1466_p2[11:1]}};

assign lshr_ln1040_1_cast_fu_1550_p4 = {{sub_ln1040_2_fu_1544_p2[11:1]}};

assign or_ln1042_fu_1720_p2 = (tmp_21_fu_1682_p3 | icmp_ln1042_fu_1700_p2);

assign or_ln1043_fu_1772_p2 = (tmp_23_fu_1734_p3 | icmp_ln1043_fu_1752_p2);

assign p_0_0_0116117401751_i_out = p_0_0_0116117401751_i_load_reg_2032;

assign p_0_0_0116217381749_i_out = p_0_0_0116217381749_i_load_reg_2026;

assign p_0_0_0116317361747_i_out = p_0_0_0116317361747_i_load_reg_2020;

assign p_0_0_01174_217341763_i_out = p_0_0_01174_217341763_i_load_reg_2065;

assign p_0_0_01175_217321761_i_out = p_0_0_01175_217321761_i_load_reg_2059;

assign p_0_0_01176_217301759_i_out = p_0_0_01176_217301759_i_load_reg_2053;

assign p_0_0_0_0_011551660_i_out = p_0_0_0_0_011551660_i_load_reg_2071;

assign p_0_1_0_0_011561663_i_out = p_0_1_0_0_011561663_i_load_reg_2077;

assign p_0_2_0_0_011571666_i_out = p_0_2_0_0_011571666_i_load_reg_2083;

assign phi_ln1046_fu_1786_p3 = ((icmp_ln1014_reg_2010_pp0_iter2_reg[0:0] == 1'b1) ? pix_reg_423_pp0_iter2_reg : select_ln1046_fu_1726_p3);

assign phi_ln1048_fu_1793_p3 = ((icmp_ln1014_reg_2010_pp0_iter2_reg[0:0] == 1'b1) ? pix_8_reg_403_pp0_iter2_reg : select_ln1048_fu_1778_p3);

assign r_0_in_i_cast1_fu_1650_p1 = r_0_in_i_fu_1644_p2;

assign r_0_in_i_fu_1644_p2 = ($signed(zext_ln1034_1_fu_1607_p1) - $signed(r_0_in_i_v_v_cast_fu_1640_p1));

assign r_0_in_i_v_v_cast_fu_1640_p1 = $signed(r_0_in_i_v_v_fu_1634_p3);

assign r_0_in_i_v_v_fu_1634_p3 = ((icmp_ln1030_reg_2134[0:0] == 1'b1) ? select_ln1033_fu_1600_p3 : select_ln1039_reg_2162);

assign right_1_out = right_4_reg_2043;

assign right_2_out = right_5_reg_2048;

assign right_out = right_3_reg_2038;

assign select_ln1033_fu_1600_p3 = ((tmp_17_fu_1584_p3[0:0] == 1'b1) ? sub_ln1033_3_reg_2146 : zext_ln_fu_1591_p4);

assign select_ln1034_fu_1627_p3 = ((tmp_18_fu_1611_p3[0:0] == 1'b1) ? sub_ln1034_3_reg_2157 : zext_ln1_fu_1618_p4);

assign select_ln1039_fu_1498_p3 = ((tmp_19_fu_1458_p3[0:0] == 1'b1) ? sub_ln1039_3_fu_1482_p2 : zext_ln2_fu_1488_p4);

assign select_ln1040_fu_1576_p3 = ((tmp_20_fu_1536_p3[0:0] == 1'b1) ? sub_ln1040_3_fu_1560_p2 : zext_ln3_fu_1566_p4);

assign select_ln1042_fu_1712_p3 = ((xor_ln1046_fu_1706_p2[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign select_ln1043_fu_1764_p3 = ((xor_ln1048_fu_1758_p2[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign select_ln1046_fu_1726_p3 = ((or_ln1042_fu_1720_p2[0:0] == 1'b1) ? select_ln1042_fu_1712_p3 : trunc_ln1046_fu_1678_p1);

assign select_ln1048_fu_1778_p3 = ((or_ln1043_fu_1772_p2[0:0] == 1'b1) ? select_ln1043_fu_1764_p3 : trunc_ln1048_fu_1674_p1);

assign select_ln957_10_fu_849_p3 = ((cmp161_i_reg_1994[0:0] == 1'b1) ? ap_phi_mux_p_0_0_01175_21732_ph_i_phi_fu_388_p4 : p_0_0_01175_217321761_i_fu_192);

assign select_ln957_11_fu_856_p3 = ((cmp161_i_reg_1994[0:0] == 1'b1) ? ap_phi_mux_p_0_0_01176_21730_ph_i_phi_fu_397_p4 : p_0_0_01176_217301759_i_fu_188);

assign select_ln957_1_fu_784_p3 = ((cmp161_i_reg_1994[0:0] == 1'b1) ? tmp_i_fu_711_p3 : right_1_fu_180);

assign select_ln957_2_fu_792_p3 = ((cmp161_i_reg_1994[0:0] == 1'b1) ? tmp_1_i_fu_720_p3 : right_2_fu_184);

assign select_ln957_3_fu_800_p3 = ((cmp161_i_reg_1994[0:0] == 1'b1) ? trunc_ln902_fu_706_p1 : p_0_0_0_0_011551660_i_fu_200);

assign select_ln957_4_fu_807_p3 = ((cmp161_i_reg_1994[0:0] == 1'b1) ? tmp_i_fu_711_p3 : p_0_1_0_0_011561663_i_fu_204);

assign select_ln957_5_fu_814_p3 = ((cmp161_i_reg_1994[0:0] == 1'b1) ? tmp_1_i_fu_720_p3 : p_0_2_0_0_011571666_i_fu_208);

assign select_ln957_6_fu_821_p3 = ((cmp161_i_reg_1994[0:0] == 1'b1) ? tmp_4_i_fu_741_p3 : p_0_0_0116117401751_i_fu_172);

assign select_ln957_7_fu_828_p3 = ((cmp161_i_reg_1994[0:0] == 1'b1) ? tmp_3_i_fu_733_p3 : p_0_0_0116217381749_i_fu_168);

assign select_ln957_8_fu_835_p3 = ((cmp161_i_reg_1994[0:0] == 1'b1) ? trunc_ln902_1_fu_729_p1 : p_0_0_0116317361747_i_fu_164);

assign select_ln957_9_fu_842_p3 = ((cmp161_i_reg_1994[0:0] == 1'b1) ? ap_phi_mux_p_0_0_01174_21734_ph_i_phi_fu_379_p4 : p_0_0_01174_217341763_i_fu_196);

assign select_ln957_fu_776_p3 = ((cmp161_i_reg_1994[0:0] == 1'b1) ? trunc_ln902_fu_706_p1 : right_fu_176);

assign sext_ln1033_1_fu_1340_p1 = $signed(sub_ln1033_1_fu_1330_p2);

assign sext_ln1033_2_fu_1350_p1 = add_ln1033_fu_1344_p2;

assign sext_ln1033_fu_1336_p1 = $signed(sub_ln1033_fu_1324_p2);

assign sext_ln1034_1_fu_1392_p1 = $signed(sub_ln1034_1_fu_1382_p2);

assign sext_ln1034_2_fu_1402_p1 = add_ln1034_fu_1396_p2;

assign sext_ln1034_fu_1388_p1 = $signed(sub_ln1034_fu_1376_p2);

assign sext_ln1039_1_fu_1444_p1 = $signed(sub_ln1039_1_fu_1434_p2);

assign sext_ln1039_2_fu_1454_p1 = add_ln1039_fu_1448_p2;

assign sext_ln1039_fu_1440_p1 = $signed(sub_ln1039_fu_1428_p2);

assign sext_ln1040_1_fu_1522_p1 = $signed(sub_ln1040_1_fu_1512_p2);

assign sext_ln1040_2_fu_1532_p1 = add_ln1040_fu_1526_p2;

assign sext_ln1040_fu_1518_p1 = $signed(sub_ln1040_fu_1506_p2);

assign sext_ln1048_fu_1670_p1 = b_0_in_i_fu_1664_p2;

assign storemerge_1_in_i_fu_911_p3 = ((cmp203_i_reg_1969[0:0] == 1'b1) ? tmp_19_i_fu_897_p6 : tmp_2_fu_863_p6);

assign sub_ln1023_fu_1030_p2 = (zext_ln1023_fu_1022_p1 - zext_ln1023_1_fu_1026_p1);

assign sub_ln1024_fu_1070_p2 = (zext_ln1024_fu_1062_p1 - zext_ln1024_1_fu_1066_p1);

assign sub_ln1025_fu_1110_p2 = (zext_ln1025_fu_1102_p1 - zext_ln1025_1_fu_1106_p1);

assign sub_ln1026_fu_1150_p2 = (zext_ln1026_fu_1142_p1 - zext_ln1026_1_fu_1146_p1);

assign sub_ln1027_fu_1190_p2 = (zext_ln1027_fu_1182_p1 - zext_ln1027_1_fu_1186_p1);

assign sub_ln1028_fu_1230_p2 = (zext_ln1028_fu_1222_p1 - zext_ln1028_1_fu_1226_p1);

assign sub_ln1033_1_fu_1330_p2 = (zext_ln1025_1_fu_1106_p1 - zext_ln1023_1_fu_1026_p1);

assign sub_ln1033_2_fu_1354_p2 = ($signed(13'd0) - $signed(sext_ln1033_2_fu_1350_p1));

assign sub_ln1033_3_fu_1370_p2 = (11'd0 - lshr_ln1033_1_cast_fu_1360_p4);

assign sub_ln1033_fu_1324_p2 = (zext_ln1025_fu_1102_p1 - zext_ln1023_fu_1022_p1);

assign sub_ln1034_1_fu_1382_p2 = (zext_ln1025_1_fu_1106_p1 - zext_ln1027_1_fu_1186_p1);

assign sub_ln1034_2_fu_1406_p2 = ($signed(13'd0) - $signed(sext_ln1034_2_fu_1402_p1));

assign sub_ln1034_3_fu_1422_p2 = (11'd0 - lshr_ln1034_1_cast_fu_1412_p4);

assign sub_ln1034_fu_1376_p2 = (zext_ln1025_fu_1102_p1 - zext_ln1027_fu_1182_p1);

assign sub_ln1039_1_fu_1434_p2 = (zext_ln1026_1_fu_1146_p1 - zext_ln1024_1_fu_1066_p1);

assign sub_ln1039_2_fu_1466_p2 = ($signed(13'd0) - $signed(sext_ln1039_2_fu_1454_p1));

assign sub_ln1039_3_fu_1482_p2 = (11'd0 - lshr_ln1039_1_cast_fu_1472_p4);

assign sub_ln1039_fu_1428_p2 = (zext_ln1026_fu_1142_p1 - zext_ln1024_fu_1062_p1);

assign sub_ln1040_1_fu_1512_p2 = (zext_ln1026_1_fu_1146_p1 - zext_ln1028_1_fu_1226_p1);

assign sub_ln1040_2_fu_1544_p2 = ($signed(13'd0) - $signed(sext_ln1040_2_fu_1532_p1));

assign sub_ln1040_3_fu_1560_p2 = (11'd0 - lshr_ln1040_1_cast_fu_1550_p4);

assign sub_ln1040_fu_1506_p2 = (zext_ln1026_fu_1142_p1 - zext_ln1028_fu_1222_p1);

assign sub_ln61_4_fu_1080_p2 = (10'd0 - trunc_ln61_4_fu_1076_p1);

assign sub_ln61_5_fu_1120_p2 = (10'd0 - trunc_ln61_5_fu_1116_p1);

assign sub_ln61_6_fu_1160_p2 = (10'd0 - trunc_ln61_6_fu_1156_p1);

assign sub_ln61_7_fu_1200_p2 = (10'd0 - trunc_ln61_7_fu_1196_p1);

assign sub_ln61_8_fu_1240_p2 = (10'd0 - trunc_ln61_8_fu_1236_p1);

assign sub_ln61_fu_1040_p2 = (10'd0 - trunc_ln61_fu_1036_p1);

assign tmp_11_fu_1046_p3 = sub_ln1023_fu_1030_p2[32'd10];

assign tmp_12_fu_1086_p3 = sub_ln1024_fu_1070_p2[32'd10];

assign tmp_13_fu_1126_p3 = sub_ln1025_fu_1110_p2[32'd10];

assign tmp_14_fu_1166_p3 = sub_ln1026_fu_1150_p2[32'd10];

assign tmp_15_fu_1206_p3 = sub_ln1027_fu_1190_p2[32'd10];

assign tmp_16_fu_1246_p3 = sub_ln1028_fu_1230_p2[32'd10];

assign tmp_17_fu_1584_p3 = add_ln1033_reg_2140[32'd11];

assign tmp_17_i_fu_877_p4 = {{lineBuffer_q1[19:10]}};

assign tmp_18_fu_1611_p3 = add_ln1034_reg_2151[32'd11];

assign tmp_18_i_fu_887_p4 = {{lineBuffer_q1[29:20]}};

assign tmp_19_fu_1458_p3 = add_ln1039_fu_1448_p2[32'd11];

assign tmp_19_i_fu_897_p6 = {{{{{tmp_18_i_fu_887_p4}, {6'd0}}, {tmp_17_i_fu_877_p4}}, {6'd0}}, {trunc_ln902_fu_706_p1}};

assign tmp_1_i_fu_720_p3 = {{lineBuffer_q1[29:20]}};

assign tmp_20_fu_1536_p3 = add_ln1040_fu_1526_p2[32'd11];

assign tmp_21_fu_1682_p3 = r_0_in_i_cast1_fu_1650_p1[32'd13];

assign tmp_22_fu_1690_p4 = {{r_0_in_i_fu_1644_p2[11:10]}};

assign tmp_23_fu_1734_p3 = sext_ln1048_fu_1670_p1[32'd13];

assign tmp_24_fu_1742_p4 = {{b_0_in_i_fu_1664_p2[11:10]}};

assign tmp_2_fu_863_p6 = {{{{{ap_phi_mux_p_0_0_01174_21734_ph_i_phi_fu_379_p4}, {6'd0}}, {ap_phi_mux_p_0_0_01175_21732_ph_i_phi_fu_388_p4}}, {6'd0}}, {ap_phi_mux_p_0_0_01176_21730_ph_i_phi_fu_397_p4}};

assign tmp_3_i_fu_733_p3 = {{lineBuffer_2_q1[19:10]}};

assign tmp_4_i_fu_741_p3 = {{lineBuffer_2_q1[29:20]}};

assign tmp_5_i_fu_922_p4 = {{storemerge_1_in_i_fu_911_p3[25:16]}};

assign tmp_6_i_fu_932_p4 = {{storemerge_1_in_i_fu_911_p3[41:32]}};

assign tmp_i_fu_711_p3 = {{lineBuffer_q1[19:10]}};

assign trunc_ln1046_fu_1678_p1 = r_0_in_i_fu_1644_p2[9:0];

assign trunc_ln1048_fu_1674_p1 = b_0_in_i_fu_1664_p2[9:0];

assign trunc_ln61_4_fu_1076_p1 = sub_ln1024_fu_1070_p2[9:0];

assign trunc_ln61_5_fu_1116_p1 = sub_ln1025_fu_1110_p2[9:0];

assign trunc_ln61_6_fu_1156_p1 = sub_ln1026_fu_1150_p2[9:0];

assign trunc_ln61_7_fu_1196_p1 = sub_ln1027_fu_1190_p2[9:0];

assign trunc_ln61_8_fu_1236_p1 = sub_ln1028_fu_1230_p2[9:0];

assign trunc_ln61_fu_1036_p1 = sub_ln1023_fu_1030_p2[9:0];

assign trunc_ln881_fu_606_p1 = ap_sig_allocacmp_z[0:0];

assign trunc_ln902_1_fu_729_p1 = lineBuffer_2_q1[9:0];

assign trunc_ln902_fu_706_p1 = lineBuffer_q1[9:0];

assign trunc_ln913_fu_749_p1 = imgRB_dout[9:0];

assign x_8_fu_600_p2 = (ap_sig_allocacmp_z + 11'd1);

assign xor_ln1014_1_fu_634_p2 = (xor_ln1014_fu_628_p2 ^ 1'd1);

assign xor_ln1014_fu_628_p2 = (trunc_ln881_fu_606_p1 ^ empty);

assign xor_ln1046_fu_1706_p2 = (tmp_21_fu_1682_p3 ^ 1'd1);

assign xor_ln1048_fu_1758_p2 = (tmp_23_fu_1734_p3 ^ 1'd1);

assign zext_ln1014_fu_640_p1 = xor_ln1014_1_fu_634_p2;

assign zext_ln1023_1_fu_1026_p1 = right_fu_176;

assign zext_ln1023_fu_1022_p1 = ap_phi_reg_pp0_iter2_left_reg_478;

assign zext_ln1024_1_fu_1066_p1 = ap_phi_reg_pp0_iter2_down_reg_451;

assign zext_ln1024_fu_1062_p1 = ap_phi_reg_pp0_iter2_up_reg_505;

assign zext_ln1025_1_fu_1106_p1 = right_1_fu_180;

assign zext_ln1025_fu_1102_p1 = ap_phi_reg_pp0_iter2_left_1_reg_469;

assign zext_ln1026_1_fu_1146_p1 = ap_phi_reg_pp0_iter2_down_1_reg_442;

assign zext_ln1026_fu_1142_p1 = ap_phi_reg_pp0_iter2_up_1_reg_496;

assign zext_ln1027_1_fu_1186_p1 = right_2_fu_184;

assign zext_ln1027_fu_1182_p1 = ap_phi_reg_pp0_iter2_left_2_reg_460;

assign zext_ln1028_1_fu_1226_p1 = ap_phi_reg_pp0_iter2_down_2_reg_433;

assign zext_ln1028_fu_1222_p1 = ap_phi_reg_pp0_iter2_up_2_reg_487;

assign zext_ln1030_1_fu_1266_p1 = DGh_fu_1134_p3;

assign zext_ln1030_2_fu_1276_p1 = add_ln1030_fu_1270_p2;

assign zext_ln1030_3_fu_1280_p1 = DBh_fu_1214_p3;

assign zext_ln1030_4_fu_1290_p1 = DRv_fu_1094_p3;

assign zext_ln1030_5_fu_1294_p1 = DGv_fu_1174_p3;

assign zext_ln1030_6_fu_1304_p1 = add_ln1030_2_fu_1298_p2;

assign zext_ln1030_7_fu_1308_p1 = DBv_fu_1254_p3;

assign zext_ln1030_fu_1262_p1 = DRh_fu_1054_p3;

assign zext_ln1034_1_fu_1607_p1 = pix_7_reg_413_pp0_iter2_reg;

assign zext_ln1_fu_1618_p4 = {{add_ln1034_reg_2151[11:1]}};

assign zext_ln2_fu_1488_p4 = {{add_ln1039_fu_1448_p2[11:1]}};

assign zext_ln3_fu_1566_p4 = {{add_ln1040_fu_1526_p2[11:1]}};

assign zext_ln881_fu_610_p1 = x_8_fu_600_p2;

assign zext_ln_fu_1591_p4 = {{add_ln1033_reg_2140[11:1]}};

endmodule //design_1_v_demosaic_0_2_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2
